package moe.n4tsu.dextop

import java.util.Locale

internal object NativeStrings {
    fun text(key: String): String {
        val language = Locale.getDefault().language
        return ((values[language] ?: values.getValue("en"))[key]
            ?: values.getValue("en")[key]
            ?: key).replace("\\n", "\n")
    }

    private val values = mapOf(
        "ja" to mapOf(
            "nativeUnknownPermissionResult" to "Shizukuから不明な権限結果が返されました",
            "nativeDevice" to "端末",
            "nativeCoverDisplay" to "カバーディスプレイ",
            "nativeCoverDisplayDescription" to "カバー画面で通常のAndroidを開くか、独立したDextopセッションを作成します",
            "nativeCoverAndroidDescription" to "カバー画面を通常のAndroidとして使用します。メイン側のDextopセッションは継続します。",
            "nativeCoverDextopDescription" to "カバー画面にメイン側とは独立したDextopセッションを作成します。",
            "nativeOpenCoverAndroid" to "通常のAndroidを開く",
            "nativeStopCoverAndroid" to "Androidセッションを終了",
            "nativeStartCoverDextop" to "カバー側にDextopセッションを作成",
            "nativeStopCoverDextop" to "カバー側のセッションを終了",
            "nativeCoverDisplayFailed" to "カバーディスプレイを変更できませんでした",
            "nativeSwitchToResolutionSuffix" to "この解像度とDPIへ切り替えます",
            "nativeShizukuUnavailable" to "Shizukuを利用できません",
            "nativeSelectedAppCannotLaunch" to "選択したアプリを起動できません",
            "nativeShizukuBinderUnavailable" to "Shizukuへの接続を利用できません",
            "nativeMirrorSurfaceUnavailable" to "ミラー表示領域を利用できません",
            "nativeRotationReleaseUnsupported" to "画面回転の固定解除に対応していません",
            "nativePerformanceHudFormat" to "%1\$.1f FPS  |  %2\$d MB\nバッテリー: %3\$d%%  |  %4\$s\nCPU温度: %6\$s  |  入力: %5\$s",
            "nativeInputMouse" to "マウス",
            "nativeInputTouch" to "タップ",
            "nativeInputTrackpad" to "トラックパッド",
            "nativeInputIdle" to "待機中",
            "nativePhysicalMouse" to "物理マウスの入力先を切り替え",
            "nativePhysicalKeyboard" to "物理キーボードの入力先を切り替え",
            "nativePhysicalMouseDemo" to "物理マウスの入力先をAndroidとDextopの間で切り替えます。対応端末で外部ディスプレイ接続中に表示されます",
            "nativePhysicalKeyboardDemo" to "物理キーボードの入力先をAndroidとDextopの間で切り替えます。対応端末で外部ディスプレイ接続中に表示されます",
            "nativeTheThreeFingerGestureIsAnEssential" to "3本指ジェスチャーはDextop使用中に必須の操作方法です。\\n各ボタンをタップすると、ここに機能の説明が表示されます",
            "nativeAsusZenuiRogUiDesktop" to "ASUS ZenUI / ROG UI デスクトップ",
            "nativeAndroidDesktopFreeform" to "Android デスクトップ（Freeform）",
            "nativeColorosDesktop" to "ColorOS 系デスクトップ",
            "nativeAdjustTheVolumeOfPlaybackOnDextop" to "Dextopで再生する音量を調整します",
            "nativeSwitchBetweenPortraitAndLandscapeOrientationOf" to "Dextopの縦向きと横向きを切り替えます",
            "nativeSwitchDextopResolutionAndDpi" to "Dextopの解像度とDPIを切り替えます",
            "nativePauseDextopAndReturnYourAndroidTo" to "Dextopを一時停止し、Androidを通常操作できる状態へ戻します",
            "nativeTerminateYourDextopSession" to "Dextopセッションを終了します",
            "nativeAdjustTheBrightnessOfTheDesktopDisplay" to "Dextop表示の明るさを調整します",
            "nativeHonorMagicosDesktop" to "HONOR MagicOS デスクトップ",
            "nativeHuaweiEmuiDesktop" to "Huawei EMUI デスクトップ",
            "nativeHyperosMiuiDesktop" to "HyperOS / MIUI デスクトップ",
            "nativeMotorolaLenovoDesktop" to "Motorola / Lenovo デスクトップ",
            "nativeNothingOsDesktop" to "Nothing OS デスクトップ",
            "nativeOriginosFuntouchOsDesktop" to "OriginOS / Funtouch OS デスクトップ",
            "nativePixelAndroidDesktop" to "Pixel Android デスクトップ",
            "nativeShizukuPermissionCheckTimedOut" to "Shizukuの権限確認がタイムアウトしました",
            "nativeRequiresConnectionToShizukuAndPermissions" to "Shizukuへの接続と権限許可が必要です",
            "nativePermissionDeniedToShizuku" to "Shizukuへの権限が拒否されました",
            "nativePleaseInstallShizuku" to "Shizukuをインストールしてください",
            "nativePleaseStartShizuku" to "Shizukuを起動してください",
            "nativeRemoveThisResolution" to "この解像度を削除",
            "nativeNoAppSelected" to "アプリが選択されていません",
            "nativeCouldNotStartApp" to "アプリを起動できませんでした",
            "nativeAddCustomResolution" to "カスタム解像度を追加",
            "nativeRotate180" to "180度回転",
            "nativeCast" to "キャスト",
            "nativeCastDescription" to "キャスト先を選択",
            "nativeNoCastDevices" to "利用可能なGoogle Castデバイスがありません",
            "nativeCastUnavailable" to "Google Castを初期化できませんでした",
            "nativeCasting" to "キャスト中",
            "nativeStopCasting" to "キャストを終了",
            "nativeScanAgain" to "再スキャン",
            "nativeScanning" to "スキャン中…",
            "nativeCursor" to "カーソル",
            "nativeTap" to "タップ",
            "nativeTapToExit" to "タップして終了",
            "nativeTapToOpen" to "タップして開く",
            "nativeYouCanRearrangeTheLayoutInThe" to "ボタンを長押しして、操作パネル内の配置を並べ替えられます",
            "nativeWorkSpace" to "ワークスペース",
            "nativeExpandWorkspace" to "ワークスペースを展開",
            "nativeTemporarilyReturnToAndroid" to "一時的にAndroidに戻る",
            "nativeLaptopMode" to "ラップトップモード",
            "nativeLaptopModeDescription" to "折りたたみ端末の下半分にキーボードとトラックパッドを表示します",
            "nativeKeyboardSettings" to "キーボード設定",
            "nativeKeyboardSettingsDescription" to "ラップトップキーボードの外観をカスタマイズします",
            "nativeTheme" to "テーマ",
            "nativeKeyboardThemeStandard" to "標準",
            "nativeKeyboardThemeCrimson" to "クリムゾン",
            "nativeKeyboardThemeCloud" to "Cloud Pop",
            "nativeKeyboardThemeAmoled" to "AMOLED",
            "nativeKeyboardThemeStandardDescription" to "落ち着いたダークキーボード",
            "nativeKeyboardThemeCrimsonDescription" to "折りたたみPCをイメージした暖色のクリムゾン",
            "nativeKeyboardThemeCloudDescription" to "やわらかな雲色のキーボード",
            "nativeKeyboardThemeAmoledDescription" to "黒を基調にした省電力キーボード",
            "nativeKeyboardThemeCustomDescription" to "カスタムキーボードテーマ",
            "nativeOpenDextopWithYourSavedAppPlacement" to "保存されたアプリ配置でDextopを開きます",
            "nativeSaveAndApply" to "保存して適用",
            "nativeFailedToSaveUnableToRetrieveRunning" to "保存できませんでした：Dextop上で起動中のアプリを取得できません。",
            "nativeFailedToSaveFailedToWriteTo" to "保存できませんでした：端末ストレージへの書き込みに失敗しました。",
            "nativeViewSavedWorkspacesAndSaveCurrentArrangement" to "保存済みワークスペースの表示と、現在の配置の保存ができます",
            "nativeNoSavedWorkspaces" to "保存済みワークスペースはありません",
            "nativePleaseStartDextopFirst" to "先にDextopを開始してください",
            "nativeReconnect" to "再接続",
            "nativeWidth" to "幅",
            "nativeReturn" to "戻る",
            "nativePermissionRequestInProgress" to "権限リクエストが進行中です",
            "nativeHorizontalHolding" to "横持ち",
            "nativeSaveTheCurrentAppArrangementAsA" to "現在のアプリ配置をワークスペースとして保存します",
            "nativeAddCurrentAppPlacement" to "現在のアプリ配置を追加",
            "nativeScreenBrightness" to "画面の明るさ",
            "nativeUseTheScreenAsATrackpadTo" to "画面をトラックパッドとして使い、カーソルを操作します",
            "nativeEnd" to "終了",
            "nativeEdit" to "編集",
            "nativeVerticalHolding" to "縦持ち",
            "nativeReconnectIfYouHaveDisplayOrConnection" to "表示や接続に問題がある場合に再接続します",
            "nativeDisplayProfileIsOutOfRange" to "表示プロファイルが範囲外です",
            "nativeResolution" to "解像度",
            "nativeEditResolution" to "解像度を編集",
            "nativeAddResolution" to "解像度を追加",
            "nativeSendsTheTouchedPositionDirectlyToDextop" to "触れた位置をDextopへ直接タップとして送ります",
            "nativeAddAndApply" to "追加して適用",
            "nativeEditPlacement" to "配置を編集",
            "nativeCompletePlacementEdit" to "配置編集を完了",
            "nativeVolume" to "音量",
            "nativeHeight" to "高さ",
        ),
        "en" to mapOf(
            "nativeUnknownPermissionResult" to "Shizuku returned an unknown permission result",
            "nativeDevice" to "Device",
            "nativeCoverDisplay" to "Cover display",
            "nativeCoverDisplayDescription" to "Open Android or create an independent Dextop session on the cover display",
            "nativeCoverAndroidDescription" to "Use the cover display for normal Android while the main Dextop session continues.",
            "nativeCoverDextopDescription" to "Create a Dextop session on the cover display independently from the main session.",
            "nativeOpenCoverAndroid" to "Open Android on cover display",
            "nativeStopCoverAndroid" to "End Android session",
            "nativeStartCoverDextop" to "Create Dextop session on cover display",
            "nativeStopCoverDextop" to "End cover Dextop session",
            "nativeCoverDisplayFailed" to "Could not update the cover display",
            "nativeSwitchToResolutionSuffix" to "Switch to this resolution and DPI",
            "nativeShizukuUnavailable" to "Shizuku is unavailable",
            "nativeSelectedAppCannotLaunch" to "The selected app cannot be launched",
            "nativeShizukuBinderUnavailable" to "The Shizuku connection is unavailable",
            "nativeMirrorSurfaceUnavailable" to "The mirror surface is unavailable",
            "nativeRotationReleaseUnsupported" to "Releasing rotation lock is not supported",
            "nativePerformanceHudFormat" to "%1\$.1f FPS  |  %2\$d MB\nBattery: %3\$d%%  |  %4\$s\nCPU: %6\$s  |  Input: %5\$s",
            "nativeInputMouse" to "Mouse",
            "nativeInputTouch" to "Touch",
            "nativeInputTrackpad" to "Trackpad",
            "nativeInputIdle" to "Idle",
            "nativePhysicalMouse" to "Switch physical mouse destination",
            "nativePhysicalKeyboard" to "Switch physical keyboard destination",
            "nativePhysicalMouseDemo" to "Switch the physical mouse between Android and Dextop. Available on supported devices while an external display is connected.",
            "nativePhysicalKeyboardDemo" to "Switch the physical keyboard between Android and Dextop. Available on supported devices while an external display is connected.",
            "nativeTheThreeFingerGestureIsAnEssential" to "The three-finger gesture is essential while using Dextop.\\nTap a button to see what it does.",
            "nativeAsusZenuiRogUiDesktop" to "ASUS ZenUI / ROG UI Desktop",
            "nativeAndroidDesktopFreeform" to "Android Desktop (Freeform)",
            "nativeColorosDesktop" to "ColorOS desktop",
            "nativeAdjustTheVolumeOfPlaybackOnDextop" to "Adjust media volume in Dextop",
            "nativeSwitchBetweenPortraitAndLandscapeOrientationOf" to "Switch Dextop between portrait and landscape",
            "nativeSwitchDextopResolutionAndDpi" to "Change Dextop resolution and DPI",
            "nativePauseDextopAndReturnYourAndroidTo" to "Pause Dextop and return Android to normal operation.",
            "nativeTerminateYourDextopSession" to "End the Dextop session",
            "nativeAdjustTheBrightnessOfTheDesktopDisplay" to "Adjust Dextop display brightness",
            "nativeHonorMagicosDesktop" to "HONOR MagicOS Desktop",
            "nativeHuaweiEmuiDesktop" to "Huawei EMUI Desktop",
            "nativeHyperosMiuiDesktop" to "HyperOS / MIUI Desktop",
            "nativeMotorolaLenovoDesktop" to "Motorola / Lenovo Desktop",
            "nativeNothingOsDesktop" to "Nothing OS Desktop",
            "nativeOriginosFuntouchOsDesktop" to "OriginOS / Funtouch OS Desktop",
            "nativePixelAndroidDesktop" to "Pixel Android Desktop",
            "nativeShizukuPermissionCheckTimedOut" to "Shizuku permission check timed out",
            "nativeRequiresConnectionToShizukuAndPermissions" to "A Shizuku connection and permission are required",
            "nativePermissionDeniedToShizuku" to "Shizuku permission was denied",
            "nativePleaseInstallShizuku" to "Please install Shizuku",
            "nativePleaseStartShizuku" to "Please start Shizuku",
            "nativeRemoveThisResolution" to "Delete this resolution",
            "nativeNoAppSelected" to "No app selected",
            "nativeCouldNotStartApp" to "Could not start app",
            "nativeAddCustomResolution" to "Add custom resolution",
            "nativeRotate180" to "Rotate 180°",
            "nativeCast" to "Cast",
            "nativeCastDescription" to "Choose a cast receiver",
            "nativeNoCastDevices" to "No Google Cast devices are available",
            "nativeCastUnavailable" to "Google Cast could not be initialized",
            "nativeCasting" to "Casting",
            "nativeStopCasting" to "Stop casting",
            "nativeScanAgain" to "Scan again",
            "nativeScanning" to "Scanning…",
            "nativeCursor" to "Cursor",
            "nativeTap" to "Tap",
            "nativeTapToExit" to "Tap to exit",
            "nativeTapToOpen" to "Tap to open",
            "nativeYouCanRearrangeTheLayoutInThe" to "You can rearrange the layout in the control panel by long-pressing the button.",
            "nativeWorkSpace" to "Workspace",
            "nativeExpandWorkspace" to "Expand workspace",
            "nativeTemporarilyReturnToAndroid" to "Temporarily return to Android",
            "nativeLaptopMode" to "Laptop mode",
            "nativeLaptopModeDescription" to "Show a keyboard and trackpad on the lower half of a foldable device.",
            "nativeKeyboardSettings" to "Keyboard settings",
            "nativeKeyboardSettingsDescription" to "Customize the appearance of the laptop keyboard",
            "nativeTheme" to "Theme",
            "nativeKeyboardThemeStandard" to "Standard",
            "nativeKeyboardThemeCrimson" to "Crimson",
            "nativeKeyboardThemeCloud" to "Cloud Pop",
            "nativeKeyboardThemeAmoled" to "AMOLED",
            "nativeKeyboardThemeStandardDescription" to "Neutral dark keyboard",
            "nativeKeyboardThemeCrimsonDescription" to "Warm crimson inspired by foldable PCs",
            "nativeKeyboardThemeCloudDescription" to "Soft cloud blue keyboard",
            "nativeKeyboardThemeAmoledDescription" to "True-black power-saving keyboard",
            "nativeKeyboardThemeCustomDescription" to "Custom keyboard theme",
            "nativeOpenDextopWithYourSavedAppPlacement" to "Open Dextop with your saved app placement",
            "nativeSaveAndApply" to "Save and apply",
            "nativeFailedToSaveUnableToRetrieveRunning" to "Failed to save: Unable to retrieve running apps on Dextop.",
            "nativeFailedToSaveFailedToWriteTo" to "Failed to save: Failed to write to device storage.",
            "nativeViewSavedWorkspacesAndSaveCurrentArrangement" to "View saved workspaces and save current arrangement",
            "nativeNoSavedWorkspaces" to "No saved workspaces",
            "nativePleaseStartDextopFirst" to "Please start Dextop first",
            "nativeReconnect" to "Reconnect",
            "nativeWidth" to "Width",
            "nativeReturn" to "Back",
            "nativePermissionRequestInProgress" to "Permission request in progress",
            "nativeHorizontalHolding" to "Landscape",
            "nativeSaveTheCurrentAppArrangementAsA" to "Save the current app arrangement as a workspace",
            "nativeAddCurrentAppPlacement" to "Add current app layout",
            "nativeScreenBrightness" to "Screen brightness",
            "nativeUseTheScreenAsATrackpadTo" to "Use the screen as a trackpad to control the cursor",
            "nativeEnd" to "End",
            "nativeEdit" to "Edit",
            "nativeVerticalHolding" to "Portrait",
            "nativeReconnectIfYouHaveDisplayOrConnection" to "Reconnect if you have display or connection problems",
            "nativeDisplayProfileIsOutOfRange" to "Display profile is out of range",
            "nativeResolution" to "Resolution",
            "nativeEditResolution" to "Edit resolution",
            "nativeAddResolution" to "Add resolution",
            "nativeSendsTheTouchedPositionDirectlyToDextop" to "Sends the touched position directly to Dextop as a tap",
            "nativeAddAndApply" to "Add and apply",
            "nativeEditPlacement" to "Edit placement",
            "nativeCompletePlacementEdit" to "Complete placement edit",
            "nativeVolume" to "Volume",
            "nativeHeight" to "Height",
        ),
        "zh" to mapOf(
            "nativeUnknownPermissionResult" to "Shizuku 返回了未知的权限结果",
            "nativeDevice" to "设备",
            "nativeCoverDisplay" to "外屏",
            "nativeCoverDisplayDescription" to "在外屏打开 Android，或创建独立的 Dextop 会话",
            "nativeCoverAndroidDescription" to "将外屏用作普通 Android，主屏上的 Dextop 会话会继续运行。",
            "nativeCoverDextopDescription" to "在外屏创建独立于主屏会话的 Dextop 会话。",
            "nativeOpenCoverAndroid" to "在外屏打开 Android",
            "nativeStopCoverAndroid" to "结束 Android 会话",
            "nativeStartCoverDextop" to "在外屏创建 Dextop 会话",
            "nativeStopCoverDextop" to "结束外屏 Dextop 会话",
            "nativeCoverDisplayFailed" to "无法更改外屏",
            "nativeSwitchToResolutionSuffix" to "切换到此分辨率和 DPI",
            "nativeShizukuUnavailable" to "Shizuku 不可用",
            "nativeSelectedAppCannotLaunch" to "无法启动所选应用",
            "nativeShizukuBinderUnavailable" to "Shizuku 连接不可用",
            "nativeMirrorSurfaceUnavailable" to "镜像显示区域不可用",
            "nativeRotationReleaseUnsupported" to "不支持解除屏幕旋转锁定",
            "nativePerformanceHudFormat" to "%1\$.1f FPS  |  %2\$d MB\n电池: %3\$d%%  |  %4\$s\nCPU: %6\$s  |  输入: %5\$s",
            "nativeInputMouse" to "鼠标",
            "nativeInputTouch" to "触摸",
            "nativeInputTrackpad" to "触控板",
            "nativeInputIdle" to "空闲",
            "nativePhysicalMouse" to "切换物理鼠标输入目标",
            "nativePhysicalKeyboard" to "切换物理键盘输入目标",
            "nativePhysicalMouseDemo" to "在 Android 和 Dextop 之间切换物理鼠标。外接显示器连接到受支持的设备时可用。",
            "nativePhysicalKeyboardDemo" to "在 Android 和 Dextop 之间切换物理键盘。外接显示器连接到受支持的设备时可用。",
            "nativeTheThreeFingerGestureIsAnEssential" to "三指手势是使用Dextop时必不可少的操作方式。 \\n点击每个按钮可在此处查看功能说明",
            "nativeAsusZenuiRogUiDesktop" to "华硕 ZenUI / ROG UI 桌面",
            "nativeAndroidDesktopFreeform" to "Android 桌面（自由格式）",
            "nativeColorosDesktop" to "ColorOS桌面",
            "nativeAdjustTheVolumeOfPlaybackOnDextop" to "调整 Dextop 上的播放音量",
            "nativeSwitchBetweenPortraitAndLandscapeOrientationOf" to "在 Dextop 的纵向和横向之间切换",
            "nativeSwitchDextopResolutionAndDpi" to "切换 Dextop 分辨率和 DPI",
            "nativePauseDextopAndReturnYourAndroidTo" to "暂停 Dextop，并使 Android 恢复正常操作。",
            "nativeTerminateYourDextopSession" to "终止您的 Dextop 会话",
            "nativeAdjustTheBrightnessOfTheDesktopDisplay" to "调整桌面显示的亮度",
            "nativeHonorMagicosDesktop" to "荣耀MagicOS桌面",
            "nativeHuaweiEmuiDesktop" to "华为EMUI桌面",
            "nativeHyperosMiuiDesktop" to "HyperOS / MIUI 桌面",
            "nativeMotorolaLenovoDesktop" to "Motorola / Lenovo 桌面",
            "nativeNothingOsDesktop" to "Nothing OS 桌面",
            "nativeOriginosFuntouchOsDesktop" to "OriginOS / Funtouch OS 桌面",
            "nativePixelAndroidDesktop" to "Pixel Android 桌面",
            "nativeShizukuPermissionCheckTimedOut" to "Shizuku 权限检查超时",
            "nativeRequiresConnectionToShizukuAndPermissions" to "需要连接到 Shizuku 并获得权限",
            "nativePermissionDeniedToShizuku" to "Shizuku 权限被拒绝",
            "nativePleaseInstallShizuku" to "请安装 Shizuku",
            "nativePleaseStartShizuku" to "请启动 Shizuku",
            "nativeRemoveThisResolution" to "删除此分辨率",
            "nativeNoAppSelected" to "未选择应用程序",
            "nativeCouldNotStartApp" to "无法启动应用程序",
            "nativeAddCustomResolution" to "添加自定义分辨率",
            "nativeRotate180" to "旋转 180°",
            "nativeCast" to "投射",
            "nativeCastDescription" to "选择投射接收器",
            "nativeNoCastDevices" to "没有可用的 Google Cast 设备",
            "nativeCastUnavailable" to "无法初始化 Google Cast",
            "nativeCasting" to "正在投射",
            "nativeStopCasting" to "停止投射",
            "nativeScanAgain" to "重新扫描",
            "nativeScanning" to "正在扫描…",
            "nativeCursor" to "光标",
            "nativeTap" to "点击",
            "nativeTapToExit" to "点击退出",
            "nativeTapToOpen" to "点击打开",
            "nativeYouCanRearrangeTheLayoutInThe" to "您可以通过长按按钮来重新排列控制面板中的布局。",
            "nativeWorkSpace" to "工作区",
            "nativeExpandWorkspace" to "展开工作区",
            "nativeTemporarilyReturnToAndroid" to "暂时返回 Android",
            "nativeLaptopMode" to "笔记本模式",
            "nativeLaptopModeDescription" to "在折叠设备的下半屏显示键盘和触控板。",
            "nativeKeyboardSettings" to "键盘设置",
            "nativeKeyboardSettingsDescription" to "自定义笔记本键盘的外观",
            "nativeTheme" to "主题",
            "nativeKeyboardThemeStandard" to "标准",
            "nativeKeyboardThemeCrimson" to "深红",
            "nativeKeyboardThemeCloud" to "Cloud Pop",
            "nativeKeyboardThemeAmoled" to "AMOLED",
            "nativeKeyboardThemeStandardDescription" to "中性的深色键盘",
            "nativeKeyboardThemeCrimsonDescription" to "灵感来自折叠电脑的暖红色",
            "nativeKeyboardThemeCloudDescription" to "柔和的云朵蓝键盘",
            "nativeKeyboardThemeAmoledDescription" to "以纯黑为主的省电键盘",
            "nativeKeyboardThemeCustomDescription" to "自定义键盘主题",
            "nativeOpenDextopWithYourSavedAppPlacement" to "使用已保存的应用布局打开 Dextop",
            "nativeSaveAndApply" to "保存并应用",
            "nativeFailedToSaveUnableToRetrieveRunning" to "保存失败：无法检索 Dextop 上正在运行的应用程序。",
            "nativeFailedToSaveFailedToWriteTo" to "保存失败：无法写入设备存储。",
            "nativeViewSavedWorkspacesAndSaveCurrentArrangement" to "查看已保存的工作区并保存当前排列",
            "nativeNoSavedWorkspaces" to "没有保存的工作区",
            "nativePleaseStartDextopFirst" to "请先启动 Dextop",
            "nativeReconnect" to "重新连接",
            "nativeWidth" to "宽度",
            "nativeReturn" to "返回",
            "nativePermissionRequestInProgress" to "权限请求正在进行中",
            "nativeHorizontalHolding" to "横向",
            "nativeSaveTheCurrentAppArrangementAsA" to "将当前应用程序排列保存为工作区",
            "nativeAddCurrentAppPlacement" to "添加当前应用布局",
            "nativeScreenBrightness" to "屏幕亮度",
            "nativeUseTheScreenAsATrackpadTo" to "使用屏幕作为触控板来控制光标",
            "nativeEnd" to "结束",
            "nativeEdit" to "编辑",
            "nativeVerticalHolding" to "纵向",
            "nativeReconnectIfYouHaveDisplayOrConnection" to "如果出现显示或连接问题，请重新连接",
            "nativeDisplayProfileIsOutOfRange" to "显示配置文件超出范围",
            "nativeResolution" to "分辨率",
            "nativeEditResolution" to "编辑分辨率",
            "nativeAddResolution" to "添加分辨率",
            "nativeSendsTheTouchedPositionDirectlyToDextop" to "将触摸位置作为点击直接发送到 Dextop",
            "nativeAddAndApply" to "添加并应用",
            "nativeEditPlacement" to "编辑布局",
            "nativeCompletePlacementEdit" to "完成布局编辑",
            "nativeVolume" to "音量",
            "nativeHeight" to "高度",
        ),
        "ko" to mapOf(
            "nativeUnknownPermissionResult" to "Shizuku에서 알 수 없는 권한 결과를 반환했습니다",
            "nativeDevice" to "기기",
            "nativeCoverDisplay" to "커버 디스플레이",
            "nativeCoverDisplayDescription" to "커버 화면에서 Android를 열거나 독립적인 Dextop 세션을 만듭니다",
            "nativeCoverAndroidDescription" to "메인 Dextop 세션을 유지한 채 커버 화면을 일반 Android로 사용합니다.",
            "nativeCoverDextopDescription" to "메인 세션과 독립된 Dextop 세션을 커버 화면에 만듭니다.",
            "nativeOpenCoverAndroid" to "커버 화면에서 Android 열기",
            "nativeStopCoverAndroid" to "Android 세션 종료",
            "nativeStartCoverDextop" to "커버 화면에 Dextop 세션 만들기",
            "nativeStopCoverDextop" to "커버 Dextop 세션 종료",
            "nativeCoverDisplayFailed" to "커버 디스플레이를 변경할 수 없습니다",
            "nativeSwitchToResolutionSuffix" to "이 해상도와 DPI로 전환합니다",
            "nativeShizukuUnavailable" to "Shizuku를 사용할 수 없습니다",
            "nativeSelectedAppCannotLaunch" to "선택한 앱을 실행할 수 없습니다",
            "nativeShizukuBinderUnavailable" to "Shizuku 연결을 사용할 수 없습니다",
            "nativeMirrorSurfaceUnavailable" to "미러 표시 영역을 사용할 수 없습니다",
            "nativeRotationReleaseUnsupported" to "화면 회전 잠금 해제를 지원하지 않습니다",
            "nativePerformanceHudFormat" to "%1\$.1f FPS  |  %2\$d MB\n배터리: %3\$d%%  |  %4\$s\nCPU: %6\$s  |  입력: %5\$s",
            "nativeInputMouse" to "마우스",
            "nativeInputTouch" to "터치",
            "nativeInputTrackpad" to "트랙패드",
            "nativeInputIdle" to "대기 중",
            "nativePhysicalMouse" to "물리 마우스 입력 대상 전환",
            "nativePhysicalKeyboard" to "물리 키보드 입력 대상 전환",
            "nativePhysicalMouseDemo" to "물리 마우스를 Android와 Dextop 사이에서 전환합니다. 지원 기기에 외부 디스플레이가 연결된 경우 사용할 수 있습니다.",
            "nativePhysicalKeyboardDemo" to "물리 키보드를 Android와 Dextop 사이에서 전환합니다. 지원 기기에 외부 디스플레이가 연결된 경우 사용할 수 있습니다.",
            "nativeTheThreeFingerGestureIsAnEssential" to "세 손가락 제스처는 Dextop 사용 중에 필수적인 조작 방법입니다. \\n각 버튼을 탭하면 여기에 기능 설명이 표시됩니다.",
            "nativeAsusZenuiRogUiDesktop" to "ASUS ZenUI / ROG UI 데스크톱",
            "nativeAndroidDesktopFreeform" to "Android 데스크톱(Freeform)",
            "nativeColorosDesktop" to "ColorOS 기반 데스크톱",
            "nativeAdjustTheVolumeOfPlaybackOnDextop" to "Dextop에서 재생할 볼륨을 조정합니다.",
            "nativeSwitchBetweenPortraitAndLandscapeOrientationOf" to "Dextop의 세로 방향과 가로 방향을 전환합니다.",
            "nativeSwitchDextopResolutionAndDpi" to "Dextop 해상도와 DPI 간 전환",
            "nativePauseDextopAndReturnYourAndroidTo" to "Dextop을 일시 중지하고 Android를 정상적으로 조작할 수 있는 상태로 되돌립니다.",
            "nativeTerminateYourDextopSession" to "Dextop 세션을 종료합니다.",
            "nativeAdjustTheBrightnessOfTheDesktopDisplay" to "Dextop 디스플레이의 밝기를 조정합니다.",
            "nativeHonorMagicosDesktop" to "HONOR MagicOS 데스크톱",
            "nativeHuaweiEmuiDesktop" to "Huawei EMUI 데스크톱",
            "nativeHyperosMiuiDesktop" to "HyperOS / MIUI 데스크톱",
            "nativeMotorolaLenovoDesktop" to "Motorola / Lenovo 데스크톱",
            "nativeNothingOsDesktop" to "Nothing OS 데스크톱",
            "nativeOriginosFuntouchOsDesktop" to "OriginOS / Funtouch OS 데스크톱",
            "nativePixelAndroidDesktop" to "Pixel Android 데스크톱",
            "nativeShizukuPermissionCheckTimedOut" to "Shizuku의 권한 확인 시간이 초과되었습니다.",
            "nativeRequiresConnectionToShizukuAndPermissions" to "Shizuku에 연결하고 권한이 필요합니다.",
            "nativePermissionDeniedToShizuku" to "Shizuku에 대한 권한이 거부되었습니다.",
            "nativePleaseInstallShizuku" to "Shizuku를 설치하십시오",
            "nativePleaseStartShizuku" to "Shizuku를 시작하십시오.",
            "nativeRemoveThisResolution" to "이 해상도 삭제",
            "nativeNoAppSelected" to "앱이 선택되지 않음",
            "nativeCouldNotStartApp" to "앱을 시작할 수 없습니다.",
            "nativeAddCustomResolution" to "맞춤 해상도 추가",
            "nativeRotate180" to "180° 회전",
            "nativeCast" to "전송",
            "nativeCastDescription" to "전송할 기기 선택",
            "nativeNoCastDevices" to "사용 가능한 Google Cast 기기가 없습니다",
            "nativeCastUnavailable" to "Google Cast를 초기화할 수 없습니다",
            "nativeCasting" to "전송 중",
            "nativeStopCasting" to "전송 중지",
            "nativeScanAgain" to "다시 검색",
            "nativeScanning" to "검색 중…",
            "nativeCursor" to "커서",
            "nativeTap" to "탭",
            "nativeTapToExit" to "탭하여 종료",
            "nativeTapToOpen" to "탭하여 열기",
            "nativeYouCanRearrangeTheLayoutInThe" to "버튼을 길게 눌러 조작 패널의 배치를 정렬할 수 있습니다.",
            "nativeWorkSpace" to "작업 공간",
            "nativeExpandWorkspace" to "작업 공간 펼치기",
            "nativeTemporarilyReturnToAndroid" to "일시적으로 Android로 돌아가기",
            "nativeLaptopMode" to "노트북 모드",
            "nativeLaptopModeDescription" to "폴더블 기기 하단에 키보드와 트랙패드를 표시합니다.",
            "nativeKeyboardSettings" to "키보드 설정",
            "nativeKeyboardSettingsDescription" to "노트북 키보드 모양을 사용자 지정합니다",
            "nativeTheme" to "테마",
            "nativeKeyboardThemeStandard" to "표준",
            "nativeKeyboardThemeCrimson" to "크림슨",
            "nativeKeyboardThemeCloud" to "Cloud Pop",
            "nativeKeyboardThemeAmoled" to "AMOLED",
            "nativeKeyboardThemeStandardDescription" to "중성적인 다크 키보드",
            "nativeKeyboardThemeCrimsonDescription" to "폴더블 PC에서 영감을 받은 따뜻한 크림슨",
            "nativeKeyboardThemeCloudDescription" to "부드러운 구름빛 블루 키보드",
            "nativeKeyboardThemeAmoledDescription" to "순수한 검정 기반의 절전 키보드",
            "nativeKeyboardThemeCustomDescription" to "사용자 지정 키보드 테마",
            "nativeOpenDextopWithYourSavedAppPlacement" to "저장된 앱 배치에서 Dextop을 엽니다.",
            "nativeSaveAndApply" to "저장하고 적용",
            "nativeFailedToSaveUnableToRetrieveRunning" to "저장할 수 없습니다. Dextop에서 실행 중인 앱을 가져올 수 없습니다.",
            "nativeFailedToSaveFailedToWriteTo" to "저장할 수 없습니다. 기기 저장소에 쓰지 못했습니다.",
            "nativeViewSavedWorkspacesAndSaveCurrentArrangement" to "저장된 작업 공간을 표시하고 현재 배치를 저장할 수 있습니다.",
            "nativeNoSavedWorkspaces" to "저장된 작업공간 없음",
            "nativePleaseStartDextopFirst" to "먼저 Dextop을 시작하십시오.",
            "nativeReconnect" to "재연결",
            "nativeWidth" to "너비",
            "nativeReturn" to "뒤로",
            "nativePermissionRequestInProgress" to "권한 요청이 진행 중입니다.",
            "nativeHorizontalHolding" to "가로",
            "nativeSaveTheCurrentAppArrangementAsA" to "현재 앱 배치를 작업공간으로 저장",
            "nativeAddCurrentAppPlacement" to "현재 앱 배치 추가",
            "nativeScreenBrightness" to "화면 밝기",
            "nativeUseTheScreenAsATrackpadTo" to "화면을 트랙패드로 사용하여 커서를 조작합니다.",
            "nativeEnd" to "종료",
            "nativeEdit" to "편집",
            "nativeVerticalHolding" to "세로",
            "nativeReconnectIfYouHaveDisplayOrConnection" to "화면 표시나 연결에 문제가 있으면 다시 연결합니다.",
            "nativeDisplayProfileIsOutOfRange" to "표시 프로필이 범위를 벗어났습니다.",
            "nativeResolution" to "해상도",
            "nativeEditResolution" to "해상도 편집",
            "nativeAddResolution" to "해상도 추가",
            "nativeSendsTheTouchedPositionDirectlyToDextop" to "터치한 위치를 Dextop에 직접 탭으로 보냅니다.",
            "nativeAddAndApply" to "추가 및 적용",
            "nativeEditPlacement" to "배치 편집",
            "nativeCompletePlacementEdit" to "배치 편집 완료",
            "nativeVolume" to "볼륨",
            "nativeHeight" to "높이",
        ),
        "ru" to mapOf(
            "nativeUnknownPermissionResult" to "Shizuku вернул неизвестный результат разрешения",
            "nativeDevice" to "Устройство",
            "nativeCoverDisplay" to "Внешний экран",
            "nativeCoverDisplayDescription" to "Открывает Android или создаёт независимый сеанс Dextop на внешнем экране",
            "nativeCoverAndroidDescription" to "Использует внешний экран для обычного Android, не завершая сеанс Dextop на основном экране.",
            "nativeCoverDextopDescription" to "Создаёт на внешнем экране независимый от основного сеанс Dextop.",
            "nativeOpenCoverAndroid" to "Открыть Android на внешнем экране",
            "nativeStopCoverAndroid" to "Завершить сеанс Android",
            "nativeStartCoverDextop" to "Создать сеанс Dextop на внешнем экране",
            "nativeStopCoverDextop" to "Завершить сеанс Dextop",
            "nativeCoverDisplayFailed" to "Не удалось изменить внешний экран",
            "nativeSwitchToResolutionSuffix" to "Переключиться на это разрешение и DPI",
            "nativeShizukuUnavailable" to "Shizuku недоступен",
            "nativeSelectedAppCannotLaunch" to "Не удалось запустить выбранное приложение",
            "nativeShizukuBinderUnavailable" to "Подключение к Shizuku недоступно",
            "nativeMirrorSurfaceUnavailable" to "Область зеркального отображения недоступна",
            "nativeRotationReleaseUnsupported" to "Снятие блокировки поворота не поддерживается",
            "nativePerformanceHudFormat" to "%1\$.1f FPS  |  %2\$d MB\nБатарея: %3\$d%%  |  %4\$s\nCPU: %6\$s  |  Ввод: %5\$s",
            "nativeInputMouse" to "Мышь",
            "nativeInputTouch" to "Касание",
            "nativeInputTrackpad" to "Трекпад",
            "nativeInputIdle" to "Ожидание",
            "nativePhysicalMouse" to "Переключить назначение физической мыши",
            "nativePhysicalKeyboard" to "Переключить назначение физической клавиатуры",
            "nativePhysicalMouseDemo" to "Переключает физическую мышь между Android и Dextop. Доступно на поддерживаемых устройствах при подключённом внешнем дисплее.",
            "nativePhysicalKeyboardDemo" to "Переключает физическую клавиатуру между Android и Dextop. Доступно на поддерживаемых устройствах при подключённом внешнем дисплее.",
            "nativeTheThreeFingerGestureIsAnEssential" to "Жест тремя пальцами необходим при работе с Dextop.\\nНажмите кнопку, чтобы увидеть описание её функции.",
            "nativeAsusZenuiRogUiDesktop" to "Рабочий стол ASUS ZenUI/ROG UI",
            "nativeAndroidDesktopFreeform" to "Рабочий стол Android (свободная форма)",
            "nativeColorosDesktop" to "Рабочий стол ColorOS",
            "nativeAdjustTheVolumeOfPlaybackOnDextop" to "Отрегулируйте громкость воспроизведения на Dextop",
            "nativeSwitchBetweenPortraitAndLandscapeOrientationOf" to "Переключение между книжной и альбомной ориентацией Dextop",
            "nativeSwitchDextopResolutionAndDpi" to "Переключение разрешения Dextop и DPI",
            "nativePauseDextopAndReturnYourAndroidTo" to "Приостановить Dextop и вернуть Android в состояние обычного управления.",
            "nativeTerminateYourDextopSession" to "Завершите сеанс Dextop",
            "nativeAdjustTheBrightnessOfTheDesktopDisplay" to "Настройка яркости дисплея рабочего стола",
            "nativeHonorMagicosDesktop" to "Рабочий стол HONOR MagicOS",
            "nativeHuaweiEmuiDesktop" to "Рабочий стол Huawei EMUI",
            "nativeHyperosMiuiDesktop" to "Рабочий стол HyperOS / MIUI",
            "nativeMotorolaLenovoDesktop" to "Рабочий стол Motorola / Lenovo",
            "nativeNothingOsDesktop" to "Рабочий стол Nothing OS",
            "nativeOriginosFuntouchOsDesktop" to "Рабочий стол OriginOS / Funtouch OS",
            "nativePixelAndroidDesktop" to "Рабочий стол Pixel Android",
            "nativeShizukuPermissionCheckTimedOut" to "Истекло время проверки разрешения Shizuku",
            "nativeRequiresConnectionToShizukuAndPermissions" to "Требуется подключение к Shizuku и разрешения.",
            "nativePermissionDeniedToShizuku" to "Разрешение Shizuku отклонено",
            "nativePleaseInstallShizuku" to "Установите Shizuku",
            "nativePleaseStartShizuku" to "Запустите Shizuku",
            "nativeRemoveThisResolution" to "Удалить это разрешение",
            "nativeNoAppSelected" to "Приложение не выбрано",
            "nativeCouldNotStartApp" to "Не удалось запустить приложение",
            "nativeAddCustomResolution" to "Добавить собственное разрешение",
            "nativeRotate180" to "Повернуть на 180°",
            "nativeCast" to "Трансляция",
            "nativeCastDescription" to "Выбрать устройство трансляции",
            "nativeNoCastDevices" to "Нет доступных устройств Google Cast",
            "nativeCastUnavailable" to "Не удалось инициализировать Google Cast",
            "nativeCasting" to "Трансляция",
            "nativeStopCasting" to "Остановить трансляцию",
            "nativeScanAgain" to "Сканировать снова",
            "nativeScanning" to "Сканирование…",
            "nativeCursor" to "Курсор",
            "nativeTap" to "Касание",
            "nativeTapToExit" to "Нажмите, чтобы выйти",
            "nativeTapToOpen" to "Нажмите, чтобы открыть",
            "nativeYouCanRearrangeTheLayoutInThe" to "Вы можете изменить расположение макета на панели управления, удерживая кнопку.",
            "nativeWorkSpace" to "Рабочая область",
            "nativeExpandWorkspace" to "Расширить рабочую область",
            "nativeTemporarilyReturnToAndroid" to "Временно вернуться в Android",
            "nativeLaptopMode" to "Режим ноутбука",
            "nativeLaptopModeDescription" to "Показать клавиатуру и тачпад на нижней половине складного устройства.",
            "nativeKeyboardSettings" to "Настройки клавиатуры",
            "nativeKeyboardSettingsDescription" to "Настройте внешний вид клавиатуры ноутбука",
            "nativeTheme" to "Тема",
            "nativeKeyboardThemeStandard" to "Стандартная",
            "nativeKeyboardThemeCrimson" to "Малиновая",
            "nativeKeyboardThemeCloud" to "Cloud Pop",
            "nativeKeyboardThemeAmoled" to "AMOLED",
            "nativeKeyboardThemeStandardDescription" to "Нейтральная тёмная клавиатура",
            "nativeKeyboardThemeCrimsonDescription" to "Тёплый малиновый цвет в стиле складных ПК",
            "nativeKeyboardThemeCloudDescription" to "Мягкая облачно-синяя клавиатура",
            "nativeKeyboardThemeAmoledDescription" to "Энергосберегающая клавиатура на чистом чёрном фоне",
            "nativeKeyboardThemeCustomDescription" to "Пользовательская тема клавиатуры",
            "nativeOpenDextopWithYourSavedAppPlacement" to "Откройте Dextop с сохраненным местом размещения приложения.",
            "nativeSaveAndApply" to "Сохраните и примените",
            "nativeFailedToSaveUnableToRetrieveRunning" to "Не удалось сохранить: невозможно получить запущенные приложения на Dextop.",
            "nativeFailedToSaveFailedToWriteTo" to "Не удалось сохранить: не удалось записать в память устройства.",
            "nativeViewSavedWorkspacesAndSaveCurrentArrangement" to "Просмотр сохраненных рабочих пространств и сохранение текущего расположения",
            "nativeNoSavedWorkspaces" to "Нет сохраненных рабочих пространств",
            "nativePleaseStartDextopFirst" to "Пожалуйста, сначала запустите Dextop",
            "nativeReconnect" to "Переподключиться",
            "nativeWidth" to "Ширина",
            "nativeReturn" to "Назад",
            "nativePermissionRequestInProgress" to "Запрос разрешения обрабатывается",
            "nativeHorizontalHolding" to "Альбомная ориентация",
            "nativeSaveTheCurrentAppArrangementAsA" to "Сохраните текущее расположение приложения как рабочую область.",
            "nativeAddCurrentAppPlacement" to "Добавить текущее место размещения приложения",
            "nativeScreenBrightness" to "Яркость экрана",
            "nativeUseTheScreenAsATrackpadTo" to "Используйте экран как трекпад для управления курсором",
            "nativeEnd" to "Завершить",
            "nativeEdit" to "Изменить",
            "nativeVerticalHolding" to "Портретная ориентация",
            "nativeReconnectIfYouHaveDisplayOrConnection" to "Переподключитесь, если у вас возникли проблемы с отображением или подключением.",
            "nativeDisplayProfileIsOutOfRange" to "Профиль дисплея находится вне диапазона",
            "nativeResolution" to "Разрешение",
            "nativeEditResolution" to "Изменить разрешение",
            "nativeAddResolution" to "Добавить разрешение",
            "nativeSendsTheTouchedPositionDirectlyToDextop" to "Отправляет положение касания непосредственно в Dextop как касание",
            "nativeAddAndApply" to "Добавить и применить",
            "nativeEditPlacement" to "Изменить место размещения",
            "nativeCompletePlacementEdit" to "Завершить редактирование места размещения",
            "nativeVolume" to "Громкость",
            "nativeHeight" to "Высота",
        ),
    )
}
