// Generated from lib/l10n/app_*.arb. Do not edit by hand.
import 'dart:ui';

abstract final class AppStrings {
  static String tr(String key) {
    final language = PlatformDispatcher.instance.locale.languageCode;
    return (_values[language] ?? _values['en']!)[key] ??
        _values['en']![key] ??
        key;
  }

  static const Map<String, Map<String, String>> _values = {
    "ja": {
      "home": "ホーム",
      "settings": "設定",
      "resolution": "解像度",
      "theme": "テーマ",
      "system": "システム",
      "light": "ライト",
      "dark": "ダーク",
      "display": "表示",
      "secureDisplay": "セキュア表示",
      "secureDisplayDescription": "保護されたコンテンツの表示を許可します",
      "mirrorBackend": "ディスプレイのミラーリング方式",
      "mirrorBackendAuto": "自動（互換性優先）",
      "mirrorBackendAutoDescription": "この端末で利用可能な最適な方式を使用します",
      "mirrorBackendWindowManager": "WindowManager",
      "mirrorBackendSurfaceControl": "SurfaceControl",
      "mirrorBackendVirtualDisplay": "VirtualDisplay",
      "updateAvailable": "アップデートがあります",
      "updateAvailableTitle": "GitHubに最新リリースが公開されています！",
      "playUpdateAvailableTitle": "Google Playにアップデートがあります",
      "playUpdateAvailableDescription": "Google Playから最新バージョンに更新できます。",
      "updateNow": "今すぐ更新",
      "checkForUpdates": "更新を確認",
      "checkingForUpdates": "更新情報を取得しています",
      "updateNotChecked": "更新情報をまだ取得していません",
      "upToDate": "最新バージョンです",
      "updateCheckFailed": "更新情報を取得できませんでした",
      "currentVersion": "現在のバージョン",
      "latestVersion": "最新バージョン",
      "openOnGitHub": "GitHubを開く",
      "close": "閉じる",
      "deviceInfo": "端末情報",
      "desktopMode": "使用するデスクトップモード",
      "accessibilitySettings": "アクセシビリティ設定",
      "accessibilityDescription": "Dextopのサービス設定を開きます",
      "appInfo": "アプリ情報",
      "licenses": "オープンソースライセンス",
      "licensesDescription": "Flutterと使用ライブラリのライセンスを表示",
      "landscape": "横向き",
      "portrait": "縦向き",
      "stopped": "停止中",
      "running": "起動中",
      "start": "起動",
      "stop": "停止",
      "customAdd": "カスタム解像度を追加",
      "editResolution": "解像度を編集",
      "add": "追加",
      "save": "保存",
      "deleteResolution": "この解像度を削除",
      "width": "幅",
      "height": "高さ",
      "protectedContent": "保護されたコンテンツの表示を許可します",
      "version": "バージョン 1.0.0",
      "setupWelcome": "Dextopへようこそ。",
      "setupTagline": "スマホ単体で、完璧なデスクトップ環境を。",
      "setupBegin": "はじめる",
      "setupPhaseTerms": "ご利用にあたって",
      "setupPhaseShizuku": "Shizuku",
      "setupPhaseDevice": "端末の確認",
      "setupPhaseDemo": "操作を体験",
      "back": "戻る",
      "continueLabel": "続ける",
      "done": "完了",
      "incomplete": "未完了",
      "setupSystemTitle": "システム機能を利用します",
      "setupSystemDescription":
          "DextopはShizukuとADBを使用し、仮想ディスプレイ、画面方向、入力、システムUIなどの挙動を制御します。",
      "setupDisclaimer":
          "端末やOSの実装差、システム更新、他のアプリとの競合などにより生じた不具合、データ損失、端末機能への影響について、開発者は責任を負いません。内容を理解したうえで使用してください。",
      "setupShizukuTitle": "Shizukuを準備",
      "setupShizukuDescription": "Dextopがシステム機能へ安全にアクセスするためにShizukuを使用します。",
      "setupInstallShizuku": "Shizukuをインストール",
      "setupConfigureShizuku": "Shizukuを設定",
      "setupShizukuHint": "Shizukuを開き、「ペアリング」に表示される順序に従って設定し、Shizukuを開始してください。",
      "setupOpenShizuku": "Shizukuを開く",
      "setupValidate": "設定が完了しましたか？ 有効性をチェック",
      "setupDextopPermission": "Dextopへの権限",
      "setupInstallPlay": "Google Playからインストール",
      "setupAllowPermission": "権限を許可",
      "setupProviderChoiceTitle": "特権サービスを選択",
      "setupProviderChoiceDescription":
          "StellarとShizukuの両方がインストールされています。Dextopで使用するサービスを選択してください。",
      "setupUseStellar": "Stellar（推奨）",
      "setupUseShizuku": "Shizuku",
      "setupRunningAsRoot": "rootでサービスを実行中です",
      "setupRootVerified": "Shizukuがrootで実行中であることを確認しました。Dextopへの権限を付与してください。",
      "setupRootNotRunning":
          "Shizukuがrootで実行中であることを確認できませんでした。rootで起動してから、もう一度確認してください。",
      "setupQuestionOpen": "Shizukuを開きましたか？",
      "setupQuestionPair": "「ペアリング」に表示された手順をすべて完了しましたか？",
      "setupQuestionStart": "Shizukuで「開始」を押し、「Shizukuは実行中です」と表示されていますか？",
      "yes": "はい",
      "no": "いいえ",
      "setupVerified": "Shizukuの設定を確認しました",
      "setupVerificationFailed":
          "Shizukuの設定または開始を確認できません。Shizuku内の手順を完了してから、もう一度確認してください。",
      "setupPermissionCheckFailed": "Shizukuの権限を確認できませんでした",
      "setupDeviceTitle": "この端末での構成",
      "model": "機種",
      "vendor": "ベンダー",
      "desktopUi": "デスクトップUI",
      "detectedResolution": "自動検出解像度",
      "loadingLabel": "取得中…",
      "setupDeviceDescription": "この情報をもとに、初回の解像度と端末固有のデスクトップ制御を設定します。",
      "setupGestureTitle": "ジェスチャーで操作パネルを呼び出しましょう",
      "setupGestureDescription": "下の3つの円へ、3本の指を同時に置いてください。",
      "uiTwoFingerTap": "2本指タップ",
      "ui3FingerTap": "3本指タップ",
      "ui4Divisions": "4分割",
      "uiDextopIsReady": "Dextopの準備ができました",
      "uiStopDextop": "Dextopを停止",
      "uiDextopCanBeRestarted": "Dextopを再開できます",
      "uiOpenDextop": "Dextopを開く",
      "uiCreateADextopSession": "Dextopセッション作成",
      "uiDextopWorkspaceJson": "DextopワークスペースJSON",
      "uiPerformanceDisplayOnDextop": "Dextop上にパフォーマンス表示",
      "uiDoNotSleepWhileRunningDextop": "Dextop実行中はスリープしない",
      "uiRealTimeDisplayOfFpsMemoryPower": "FPS、メモリ、消費電力、バッテリーをリアルタイム表示",
      "uiCouldNotLoadJson": "JSONを読み込めませんでした",
      "uiSecureSettingsPermission": "Secure Settings権限",
      "uiAllowShizukuPermissions": "Shizuku の権限を許可",
      "uiInstallShizuku": "Shizuku をインストール",
      "uiCheckingShizukuConnection": "Shizuku 接続確認中",
      "uiShizukuConnection": "Shizuku接続",
      "uiCopy": "のコピー",
      "uiOthers": "その他",
      "uiAccessibilityOverlay": "アクセシビリティオーバーレイ",
      "uiAccessibilityServices": "アクセシビリティサービス",
      "uiAppNotFound": "アプリが見つかりません",
      "uiAppsAndWorkspace": "アプリとワークスペース",
      "uiLaunchTheAppAndConfigureYourWorkspace": "アプリの起動とワークスペースの構成",
      "uiRestartTheApp": "アプリを再起動",
      "uiSearchApp": "アプリを検索",
      "uiAppMemory": "アプリメモリ",
      "uiAppLauncher": "アプリランチャー",
      "uiAppLauncherSettings": "アプリランチャー設定",
      "uiAppLaunchFunction": "アプリ起動機能",
      "uiImport": "インポート",
      "uiExport": "エクスポート",
      "uiCursor": "カーソル",
      "uiCancel": "キャンセル",
      "uiQuickSettingsTile": "クイック設定タイル",
      "uiGesture": "ジェスチャー",
      "uiSecondaryIme": "セカンダリIME",
      "uiSecureDisplayFoldable": "セキュア表示、ミラーリング方式、Foldable",
      "uiSecurity": "セキュリティ",
      "uiTap": "タップ",
      "uiTapPressAndHoldMultiFingerOperation": "タップ、長押し、複数指操作",
      "uiOpenAppOnDesktop": "デスクトップでアプリを開く",
      "uiDesktopMode": "デスクトップモード",
      "uiDesktopFeatures": "デスクトップ機能",
      "uiTrackpad": "トラックパッド",
      "uiDrag": "ドラッグ",
      "uiBattery": "バッテリー",
      "uiPerformance": "パフォーマンス",
      "uiPerformanceCompatibility": "パフォーマンス、互換性",
      "uiItSupportsMultiTouchAndTheThree": "マルチタッチに対応し、3本指ジェスチャーは画面左からに変更されます。",
      "uiMainLarge2Sub": "メイン大・サブ2枚",
      "uiMainLeft": "メイン（左）",
      "uiLayout": "レイアウト",
      "uiWorkSpace": "ワークスペース",
      "uiCopiedWorkspaceJsonToClipboard": "ワークスペースJSONをクリップボードへコピーしました",
      "uiImportWorkspace": "ワークスペースをインポート",
      "uiSaveWorkspace": "ワークスペースを保存",
      "uiDeleteWorkspace": "ワークスペースを削除",
      "uiEditWorkspace": "ワークスペースを編集",
      "uiUp": "上へ",
      "uiDividedIntoUpperAndLowerParts": "上下2分割",
      "uiUpperHalf": "上半分",
      "uiMoveDown": "下へ移動",
      "uiLowerHalf": "下半分",
      "uiCenter": "中央",
      "uiCompatibilityDiagnosis": "互換性診断",
      "uiVirtualDisplayCreation": "仮想ディスプレイ作成",
      "uiOpenASavedAppConfiguration": "保存したアプリ構成を開く",
      "uiNoSavedWorkspaces": "保存済みワークスペースはありません",
      "uiInputAndGestures": "入力とジェスチャー",
      "uiInputMode": "入力モード",
      "uiCancelFullScreen": "全画面を解除",
      "uiReDiagnosis": "再診断",
      "uiRestart": "再開",
      "uiAvailableMemory": "利用可能メモリ",
      "uiDelete": "削除",
      "uiYouCanRestoreYourPreviousSession": "前回のセッションを復旧できます",
      "uiRight": "右",
      "uiRight13": "右1/3",
      "uiRight23": "右2/3",
      "uiRightClick": "右クリック",
      "uiUpperRight": "右上",
      "uiLowerRight": "右下",
      "uiRightHalf": "右半分",
      "uiName": "名前",
      "uiLargeScreenFoldable": "大画面・Foldable",
      "uiActualFps": "実測FPS",
      "uiExperimentalMultiTouch": "実験的なマルチタッチ",
      "uiExperimentalFeatures": "実験的な機能",
      "uiLeft": "左",
      "uiLeft13": "左1/3",
      "uiLeft13Right23": "左1/3・右2/3",
      "uiLeft23": "左2/3",
      "uiLeft23Right13": "左2/3・右1/3",
      "uiLeftCenterRight": "左・中央・右",
      "uiUpperLeft": "左上",
      "uiUpperLeftUpperRightLowerHalf": "左上・右上・下半分",
      "uiLowerLeft": "左下",
      "uiLeftHalf": "左半分",
      "uiDividedIntoLeftAndRight": "左右2分割",
      "uiSwipeRightWithThreeFingersFromThe": "左端から3本指で右へスワイプ",
      "uiRecoverySession": "復旧セッション",
      "uiEstimatedPowerConsumption": "推定消費電力",
      "uiOperationOverlay": "操作オーバーレイ",
      "uiShowActionOverlay": "操作オーバーレイを表示",
      "uiOperationMenu": "操作メニュー",
      "uiThereIsAnExistingSession": "既存のセッションがあります",
      "uiSaveConfiguration": "構成を保存",
      "uiRestorePrivileges": "権限を復旧",
      "uiChangeToHorizontalHold": "横持ちに変更",
      "uiPreparationIsRequired": "準備が必要です",
      "uiPhysicalKeyboard": "物理キーボード",
      "uiPhysicalMouse": "物理マウス",
      "uiConditionAndDiagnosis": "状態と診断",
      "uiPreventsTheScreenFromTurningOffAutomatically": "画面の自動消灯を防止します",
      "uiDestruction": "破棄",
      "uiTerminalAndPermissions": "端末と権限",
      "uiDeviceInformationDesktopModeAccessibility": "端末情報、デスクトップモード、アクセシビリティ",
      "uiTerminalResolution": "端末解像度",
      "uiEnd": "終了",
      "uiTerminationProcessingCompletedSuccessfully": "終了処理は正常に完了しました。",
      "uiEdit": "編集",
      "uiChangeToPortraitOrientation": "縦持ちに変更",
      "uiVerticalHorizontalSwitching": "縦横切り替え",
      "uiDisplayOptimization": "表示の最適化",
      "uiDisplayRefreshRate": "表示リフレッシュレート",
      "uiReproduction": "複製",
      "uiManageLaunchedAppsAndConfigurations": "起動するアプリと構成の管理",
      "uiCouldNotStart": "起動できませんでした",
      "uiLongPress": "長押し",
      "uiAutomaticallyUsesMeasuredResolutionForOpenAnd":
          "開いた状態と閉じた状態の実測解像度を自動使用",
      "uiStart": "開始",
      "uiAutomaticSwitchingAccordingToOpenClosedState": "開閉状態に合わせて自動切り替え",
      "uiOpeningQuote": "「",
      "uiDeleteWorkspaceQuestionSuffix": "」を削除しますか？",
      "uiAbnormalSessionWarning":
          "不正な状態でセッションが終了されたため、\n一部のAndroid側の機能が無効化されている可能性があります。",
      "uiChecking": "確認中",
      "uiIdle": "待機中",
      "uiAvailable": "Available",
      "uiUnavailable": "Unavailable",
      "appName": "Dextop",
      "uiAndroid": "Android",
      "uiGitHub": "GitHub",
      "uiGitHubRepository": "NarYuki/Dextop",
      "diagnosticLog": "動作ログと端末診断",
      "diagnosticLogDescription": "アプリのログ、能力判定、端末の詳細スペックを表示します",
      "loadDiagnosticLog": "診断レポートを読み込む",
      "copyDiagnosticLog": "コピー",
      "shareDiagnosticLog": "共有",
      "clearDiagnosticLog": "ログを消去",
      "deviceReport": "動作報告",
      "uiCpuTemperature": "CPU温度",
      "deviceReportDescription": "端末情報と機能の対応状況をメールで報告",
      "deviceReportIntro": "端末情報は自動収集されます。各機能の動作状況を選択してください。",
      "reportWorking": "動作した",
      "reportNotWorking": "動作しない",
      "reportUntested": "未確認",
      "reportOverall": "総合的な動作状況",
      "reportNotes": "その他・特記事項",
      "sendDeviceReport": "メールで動作報告を送る",
      "reportEmailUnavailable": "メールアプリを開けませんでした",
      "reportTemplateTitle": "Dextop端末動作報告",
      "reportNoNotes": "なし",
      "reportNoSessionLog": "完了したDextopセッションのログはまだありません。",
      "reportFeatureStartup": "アプリ起動と端末検出",
      "reportFeatureSession": "Dextopセッションの起動",
      "reportFeatureVirtualDisplay": "VirtualDisplayミラーリング",
      "reportFeatureWindowManager": "WindowManagerミラーリング",
      "reportFeatureSurfaceControl": "SurfaceControlミラーリング",
      "reportFeatureLandscape": "横向きモード",
      "reportFeaturePortrait": "縦向きモード",
      "reportFeatureSecureDisplay": "セキュア表示",
      "reportFeatureLauncher": "アプリランチャーとフリーフォームウィンドウ",
      "reportFeatureWorkspace": "ワークスペースの保存と復元",
      "reportFeatureCursor": "カーソル・タッチパッド入力",
      "reportFeatureDirectTouch": "ダイレクトタッチ入力",
      "reportFeatureMultiTouch": "マルチタッチのスクロールとピンチズーム",
      "reportFeatureGesture": "3本指オーバーレイジェスチャー",
      "reportFeatureMouse": "物理マウス",
      "reportFeatureKeyboard": "物理キーボード",
      "reportFeatureRouting": "物理マウス・キーボードのディスプレイルーティング",
      "reportFeatureFoldable": "折りたたみ端末の自動解像度",
      "reportFeaturePerformance": "パフォーマンスオーバーレイ",
      "reportFeatureCleanup": "セッション終了処理とAndroid状態の復元",
      "samsungExperimentalTitle": "実験的なSamsungデスクトップ設定",
      "samsungUnavailable": "Samsung端末でのみ利用できます",
      "samsungExperimentalDescription": "純正DeX設定で非表示になる項目をDextopから変更します",
      "samsungSettingsTitle": "Samsungデスクトップ設定",
      "samsungSettingsSummary": "表示・入力・タスクバー設定",
      "samsungRestoreSuccess": "Samsung設定を元の環境へ復元しました",
      "samsungConfirmTitle": "設定変更の確認",
      "samsungPermanentWarning":
          "この項目はDextopの体験と通常使用時のデスクトップ環境に恒久的（初期化されるまで）な影響を及ぼす可能性があります。",
      "samsungAcceptEnable": "同意して有効化",
      "samsungAboutSetting": "この設定について",
      "samsungRestoreEnvironment": "環境を復元",
      "samsungSettingsIntro":
          "Samsung純正設定が外部ディスプレイ未接続として隠すDeX設定値を直接変更します。変更はSamsung DeXと対応するDextop機能に反映されます。",
      "samsungResolution": "外部画面の解像度",
      "samsungScreenZoom": "画面ズーム（DPI）",
      "samsungFontScale": "フォントサイズ",
      "samsungScreenTimeout": "画面タイムアウト",
      "samsungAudioOutput": "外部画面から音声を出力",
      "samsungDisplayOrientation": "外部画面の回転",
      "samsungDisplayArrangement": "画面配置",
      "samsungSectionInput": "入力",
      "samsungSectionDesktop": "デスクトップ",
      "samsungInputLockedWhileRunning": "Dextop使用中は、競合するSamsung入力設定を変更できません。",
      "samsungAutorunTouchpad": "タッチパッドを自動起動",
      "samsungTouchpadScrollDirection": "スクロール方向を反転",
      "samsungTouchKeyboard": "接続時に画面キーボードを表示",
      "samsungKeyboardDex": "物理キーボード使用中も表示",
      "samsungSpenInputMode": "S Penをマウスとして使用",
      "samsungThreeFingerGesture": "3本指ジェスチャー",
      "samsungFourFingerGesture": "4本指ジェスチャー",
      "samsungAutoHideTaskbar": "タスクバーを自動的に隠す",
      "samsungDexCommandArrow": "コマンド矢印を表示",
      "samsungIncludePhoneDisplay": "端末画面をディスプレイトポロジーに含める",
      "samsungMirrorPhoneDisplay": "端末画面をミラーリング",
      "samsungReviewEnable": "注意事項を確認して設定変更を有効化",
      "samsungSeconds15": "15秒",
      "samsungSeconds30": "30秒",
      "samsungMinute1": "1分",
      "samsungMinutes2": "2分",
      "samsungMinutes5": "5分",
      "samsungMinutes10": "10分",
      "samsungMinutes20": "20分",
      "samsungMinutes30": "30分",
      "samsungHour1": "1時間",
      "samsungLeft": "左",
      "samsungRight": "右",
      "samsungAutomatic": "自動",
      "samsungGestureNone": "なし",
      "samsungGestureApps": "アプリ一覧",
      "samsungGestureRecents": "履歴",
      "samsungGestureNotifications": "通知",
      "samsungGestureQuickSettings": "クイック設定",
      "samsungHelp_resolution":
          "Samsungデスクトップ環境が使用する外部画面解像度です。Dextopの解像度設定とは別に保存されます。",
      "samsungHelp_screenZoom": "Samsungデスクトップ環境の表示密度（DPI）を変更します。",
      "samsungHelp_fontScale": "Samsungデスクトップ環境内の文字倍率を変更します。",
      "samsungHelp_screenTimeout": "外部デスクトップ画面が消灯するまでの時間です。",
      "samsungHelp_audioOutput": "音声出力先を外部画面側へ切り替えます。",
      "samsungHelp_displayOrientation": "外部デスクトップ画面の回転方向を固定します。",
      "samsungHelp_displayArrangement": "端末画面と外部画面の相対位置を指定します。",
      "samsungHelp_autorunTouchpad":
          "接続時にSamsungタッチパッドを自動表示します。Dextopの入力処理と競合します。",
      "samsungHelp_touchpadScrollDirection": "Samsungタッチパッドのスクロール方向を反転します。",
      "samsungHelp_touchKeyboard":
          "デスクトップ接続時に画面キーボードを表示します。DextopのIME制御と競合します。",
      "samsungHelp_keyboardDex": "物理キーボード接続中も画面キーボードを表示します。DextopのIME制御と競合します。",
      "samsungHelp_spenInputMode": "S Penをポインティングデバイスとして扱います。",
      "samsungHelp_threeFingerGesture":
          "Samsung側の3本指操作です。Dextopの3本指ジェスチャーと競合します。",
      "samsungHelp_fourFingerGesture":
          "Samsung側の4本指操作です。Dextopのマルチタッチ処理と競合します。",
      "samsungHelp_autoHideTaskbar": "Samsungデスクトップのタスクバーを自動的に隠します。",
      "samsungHelp_dexCommandArrow": "Samsungデスクトップのコマンド矢印を表示します。",
      "samsungHelp_includePhoneDisplay": "端末画面をデスクトップの画面配置へ含めます。",
      "samsungHelp_mirrorPhoneDisplay": "端末内蔵画面の内容をデスクトップ側へミラーリングします。",
    },
    "en": {
      "home": "Home",
      "settings": "Settings",
      "resolution": "Resolution",
      "theme": "Theme",
      "system": "System",
      "light": "Light",
      "dark": "Dark",
      "display": "Display",
      "secureDisplay": "Secure display",
      "secureDisplayDescription": "Allow protected content to be displayed",
      "mirrorBackend": "Display mirroring method",
      "mirrorBackendAuto": "Automatic (compatibility)",
      "mirrorBackendAutoDescription":
          "Use the best available method for this device",
      "mirrorBackendWindowManager": "WindowManager",
      "mirrorBackendSurfaceControl": "SurfaceControl",
      "mirrorBackendVirtualDisplay": "VirtualDisplay",
      "updateAvailable": "Update available",
      "updateAvailableTitle": "A new release is available on GitHub!",
      "playUpdateAvailableTitle": "An update is available on Google Play",
      "playUpdateAvailableDescription":
          "You can update to the latest version through Google Play.",
      "updateNow": "Update now",
      "checkForUpdates": "Check for updates",
      "checkingForUpdates": "Retrieving update information",
      "updateNotChecked": "Update information has not been retrieved yet",
      "upToDate": "You are up to date",
      "updateCheckFailed": "Could not retrieve update information",
      "currentVersion": "Current",
      "latestVersion": "Latest",
      "openOnGitHub": "Open on GitHub",
      "close": "Close",
      "deviceInfo": "Device information",
      "desktopMode": "Desktop mode in use",
      "accessibilitySettings": "Accessibility settings",
      "accessibilityDescription": "Open Dextop service settings",
      "appInfo": "App information",
      "licenses": "Open-source licenses",
      "licensesDescription": "View Flutter and dependency licenses",
      "landscape": "Landscape",
      "portrait": "Portrait",
      "stopped": "Stopped",
      "running": "Running",
      "start": "Start",
      "stop": "Stop",
      "customAdd": "Add custom resolution",
      "editResolution": "Edit resolution",
      "add": "Add",
      "save": "Save",
      "deleteResolution": "Delete this resolution",
      "width": "Width",
      "height": "Height",
      "protectedContent": "Allow protected content to be displayed",
      "version": "Version 1.0.0",
      "setupWelcome": "Welcome to Dextop.",
      "setupTagline": "A perfect desktop environment on your smartphone.",
      "setupBegin": "Start",
      "setupPhaseTerms": "Terms of use",
      "setupPhaseShizuku": "Shizuku",
      "setupPhaseDevice": "Check your device",
      "setupPhaseDemo": "Try the controls",
      "back": "Back",
      "continueLabel": "Continue",
      "done": "Done",
      "incomplete": "Incomplete",
      "setupSystemTitle": "Uses system-level features",
      "setupSystemDescription":
          "Dextop uses Shizuku and ADB to control behavior such as virtual displays, screen orientation, input, and system UI.",
      "setupDisclaimer":
          "The developer is not responsible for any defects, data loss, or impact on device functionality caused by differences in device or OS implementation, system updates, conflicts with other apps, etc. Please understand the contents before use.",
      "setupShizukuTitle": "Prepare Shizuku",
      "setupShizukuDescription":
          "Dextop uses Shizuku to securely access system functions.",
      "setupInstallShizuku": "Install Shizuku",
      "setupConfigureShizuku": "Set up Shizuku",
      "setupShizukuHint":
          "Open Shizuku, follow the steps under \"Pairing\" in order, then start Shizuku.",
      "setupOpenShizuku": "Open Shizuku",
      "setupValidate": "Finished setup? Verify now",
      "setupDextopPermission": "Dextop permission",
      "setupInstallPlay": "Install from Google Play",
      "setupAllowPermission": "Grant permission",
      "setupProviderChoiceTitle": "Choose a privilege service",
      "setupProviderChoiceDescription":
          "Stellar and Shizuku are both installed. Choose which service Dextop should use.",
      "setupUseStellar": "Stellar (recommended)",
      "setupUseShizuku": "Shizuku",
      "setupRunningAsRoot": "The service is running as root",
      "setupRootVerified":
          "Shizuku was verified as running with root privileges. Grant Dextop permission next.",
      "setupRootNotRunning":
          "Shizuku could not be verified as running with root privileges. Start it with root and try again.",
      "setupQuestionOpen": "Have you opened Shizuku?",
      "setupQuestionPair":
          "Have you completed all the steps listed under \"Pairing\"?",
      "setupQuestionStart":
          "Did you tap \"Start\" in Shizuku and confirm that it says \"Shizuku is running\"?",
      "yes": "Yes",
      "no": "No",
      "setupVerified": "Shizuku setup verified",
      "setupVerificationFailed":
          "Could not verify that Shizuku is configured and running. Complete the steps in Shizuku, then try again.",
      "setupPermissionCheckFailed": "Could not check permissions for Shizuku",
      "setupDeviceTitle": "Configuration on this device",
      "model": "Model",
      "vendor": "Vendor",
      "desktopUi": "Desktop UI",
      "detectedResolution": "Automatically detected resolution",
      "loadingLabel": "Loading…",
      "setupDeviceDescription":
          "This information is used to set the initial resolution and device-specific desktop controls.",
      "setupGestureTitle": "Open the control panel with a gesture",
      "setupGestureDescription":
          "Place three fingers on the three circles below at the same time.",
      "uiTwoFingerTap": "Two-finger tap",
      "ui3FingerTap": "Three-finger tap",
      "ui4Divisions": "Four-way split",
      "uiDextopIsReady": "Dextop is ready",
      "uiStopDextop": "Stop Dextop",
      "uiDextopCanBeRestarted": "Dextop can be resumed",
      "uiOpenDextop": "Open Dextop",
      "uiCreateADextopSession": "Create a Dextop session",
      "uiDextopWorkspaceJson": "Dextop workspace JSON",
      "uiPerformanceDisplayOnDextop": "Show performance overlay in Dextop",
      "uiDoNotSleepWhileRunningDextop":
          "Keep screen awake while Dextop is running",
      "uiRealTimeDisplayOfFpsMemoryPower":
          "Show FPS, memory, power usage, and battery in real time",
      "uiCouldNotLoadJson": "Could not load JSON",
      "uiSecureSettingsPermission": "Secure Settings permission",
      "uiAllowShizukuPermissions": "Allow Shizuku permissions",
      "uiInstallShizuku": "Install Shizuku",
      "uiCheckingShizukuConnection": "Checking Shizuku connection",
      "uiShizukuConnection": "Shizuku connection",
      "uiCopy": " copy",
      "uiOthers": "Other",
      "uiAccessibilityOverlay": "Accessibility overlay",
      "uiAccessibilityServices": "Accessibility service",
      "uiAppNotFound": "App not found",
      "uiAppsAndWorkspace": "Apps and workspace",
      "uiLaunchTheAppAndConfigureYourWorkspace":
          "Launch apps and configure workspaces",
      "uiRestartTheApp": "Restart app",
      "uiSearchApp": "Search apps",
      "uiAppMemory": "App memory",
      "uiAppLauncher": "App launcher",
      "uiAppLauncherSettings": "App launcher settings",
      "uiAppLaunchFunction": "App launch function",
      "uiImport": "Import",
      "uiExport": "Export",
      "uiCursor": "Cursor",
      "uiCancel": "Cancel",
      "uiQuickSettingsTile": "Quick Settings tile",
      "uiGesture": "Gesture",
      "uiSecondaryIme": "Secondary IME",
      "uiSecureDisplayFoldable": "Secure display, mirroring method, Foldable",
      "uiSecurity": "Security",
      "uiTap": "Tap",
      "uiTapPressAndHoldMultiFingerOperation":
          "Tap, long press, and multi-finger controls",
      "uiOpenAppOnDesktop": "Open app on desktop",
      "uiDesktopMode": "Desktop mode",
      "uiDesktopFeatures": "Desktop features",
      "uiTrackpad": "Trackpad",
      "uiDrag": "Drag",
      "uiBattery": "Battery",
      "uiPerformance": "Performance",
      "uiPerformanceCompatibility": "Performance and compatibility",
      "uiItSupportsMultiTouchAndTheThree":
          "Enables multi-touch and changes the three-finger gesture to a swipe from the left edge.",
      "uiMainLarge2Sub": "Large main + two secondary",
      "uiMainLeft": "Main (left)",
      "uiLayout": "Layout",
      "uiWorkSpace": "Workspace",
      "uiCopiedWorkspaceJsonToClipboard": "Copied workspace JSON to clipboard",
      "uiImportWorkspace": "Import workspace",
      "uiSaveWorkspace": "Save workspace",
      "uiDeleteWorkspace": "Delete workspace",
      "uiEditWorkspace": "Edit workspace",
      "uiUp": "Move up",
      "uiDividedIntoUpperAndLowerParts": "Top/bottom split",
      "uiUpperHalf": "Top half",
      "uiMoveDown": "Move down",
      "uiLowerHalf": "Bottom half",
      "uiCenter": "Center",
      "uiCompatibilityDiagnosis": "Compatibility diagnostics",
      "uiVirtualDisplayCreation": "Virtual display creation",
      "uiOpenASavedAppConfiguration": "Open a saved app configuration",
      "uiNoSavedWorkspaces": "No saved workspaces",
      "uiInputAndGestures": "Input and gestures",
      "uiInputMode": "Input mode",
      "uiCancelFullScreen": "Exit full screen",
      "uiReDiagnosis": "Run diagnostics again",
      "uiRestart": "Resume",
      "uiAvailableMemory": "Available memory",
      "uiDelete": "Delete",
      "uiYouCanRestoreYourPreviousSession":
          "You can restore your previous session",
      "uiRight": "Right",
      "uiRight13": "Right 1/3",
      "uiRight23": "Right 2/3",
      "uiRightClick": "Right click",
      "uiUpperRight": "Top right",
      "uiLowerRight": "Bottom right",
      "uiRightHalf": "Right half",
      "uiName": "Name",
      "uiLargeScreenFoldable": "Large screen/Foldable",
      "uiActualFps": "Actual FPS",
      "uiExperimentalMultiTouch": "Experimental multi-touch",
      "uiExperimentalFeatures": "Experimental features",
      "uiLeft": "Left",
      "uiLeft13": "Left 1/3",
      "uiLeft13Right23": "Left 1/3 + right 2/3",
      "uiLeft23": "Left 2/3",
      "uiLeft23Right13": "Left 2/3 + right 1/3",
      "uiLeftCenterRight": "Left / center / right",
      "uiUpperLeft": "Top left",
      "uiUpperLeftUpperRightLowerHalf": "Upper left, upper right, lower half",
      "uiLowerLeft": "Bottom left",
      "uiLeftHalf": "Left half",
      "uiDividedIntoLeftAndRight": "Left/right split",
      "uiSwipeRightWithThreeFingersFromThe":
          "Swipe right with three fingers from the left edge",
      "uiRecoverySession": "Session recovery",
      "uiEstimatedPowerConsumption": "Estimated power consumption",
      "uiOperationOverlay": "Control overlay",
      "uiShowActionOverlay": "Show control overlay",
      "uiOperationMenu": "Control menu",
      "uiThereIsAnExistingSession": "There is an existing session",
      "uiSaveConfiguration": "Save configuration",
      "uiRestorePrivileges": "Restore permissions",
      "uiChangeToHorizontalHold": "Switch to landscape",
      "uiPreparationIsRequired": "Setup required",
      "uiPhysicalKeyboard": "Physical keyboard",
      "uiPhysicalMouse": "Physical mouse",
      "uiConditionAndDiagnosis": "Status and diagnostics",
      "uiPreventsTheScreenFromTurningOffAutomatically":
          "Prevents the screen from turning off automatically",
      "uiDestruction": "Discard",
      "uiTerminalAndPermissions": "Device and permissions",
      "uiDeviceInformationDesktopModeAccessibility":
          "Device information, desktop mode, accessibility",
      "uiTerminalResolution": "Device resolution",
      "uiEnd": "End",
      "uiTerminationProcessingCompletedSuccessfully":
          "Session ended successfully.",
      "uiEdit": "Edit",
      "uiChangeToPortraitOrientation": "Switch to portrait",
      "uiVerticalHorizontalSwitching": "Portrait / landscape",
      "uiDisplayOptimization": "Display optimization",
      "uiDisplayRefreshRate": "Display refresh rate",
      "uiReproduction": "Duplicate",
      "uiManageLaunchedAppsAndConfigurations":
          "Manage apps to launch and their layouts",
      "uiCouldNotStart": "Could not start",
      "uiLongPress": "Long press",
      "uiAutomaticallyUsesMeasuredResolutionForOpenAnd":
          "Automatically uses measured resolution for open and closed states",
      "uiStart": "Start",
      "uiAutomaticSwitchingAccordingToOpenClosedState":
          "Automatic switching according to open/closed state",
      "uiOpeningQuote": "“",
      "uiDeleteWorkspaceQuestionSuffix": "” — delete this workspace?",
      "uiAbnormalSessionWarning":
          "The session ended in an invalid state.\nSome Android system functions may still be disabled.",
      "uiChecking": "Checking",
      "uiIdle": "Idle",
      "uiAvailable": "Available",
      "uiUnavailable": "Unavailable",
      "appName": "Dextop",
      "uiAndroid": "Android",
      "uiGitHub": "GitHub",
      "uiGitHubRepository": "NarYuki/Dextop",
      "diagnosticLog": "Operation log and device diagnostics",
      "diagnosticLogDescription":
          "View app logs, capability detection, and detailed device specifications",
      "loadDiagnosticLog": "Load diagnostic report",
      "copyDiagnosticLog": "Copy",
      "shareDiagnosticLog": "Share",
      "clearDiagnosticLog": "Clear log",
      "deviceReport": "Device report",
      "uiCpuTemperature": "CPU temperature",
      "deviceReportDescription":
          "Report device and feature compatibility by email",
      "deviceReportIntro":
          "Device details are collected automatically. Select the result for each feature.",
      "reportWorking": "Working",
      "reportNotWorking": "Not working",
      "reportUntested": "Not tested",
      "reportOverall": "Overall status",
      "reportNotes": "Other notes",
      "sendDeviceReport": "Send report by email",
      "reportEmailUnavailable": "Could not open an email app",
      "reportTemplateTitle": "Dextop device report",
      "reportNoNotes": "None",
      "reportNoSessionLog":
          "No completed Dextop session has been recorded yet.",
      "reportFeatureStartup": "App startup and device detection",
      "reportFeatureSession": "Dextop session startup",
      "reportFeatureVirtualDisplay": "VirtualDisplay mirroring",
      "reportFeatureWindowManager": "WindowManager mirroring",
      "reportFeatureSurfaceControl": "SurfaceControl mirroring",
      "reportFeatureLandscape": "Landscape mode",
      "reportFeaturePortrait": "Portrait mode",
      "reportFeatureSecureDisplay": "Secure display",
      "reportFeatureLauncher": "App launcher and freeform windows",
      "reportFeatureWorkspace": "Workspace save and restore",
      "reportFeatureCursor": "Cursor and touchpad input",
      "reportFeatureDirectTouch": "Direct-touch input",
      "reportFeatureMultiTouch": "Multi-touch scrolling and pinch zoom",
      "reportFeatureGesture": "Three-finger overlay gesture",
      "reportFeatureMouse": "Physical mouse",
      "reportFeatureKeyboard": "Physical keyboard",
      "reportFeatureRouting": "Physical mouse and keyboard display routing",
      "reportFeatureFoldable": "Foldable automatic resolution",
      "reportFeaturePerformance": "Performance overlay",
      "reportFeatureCleanup": "Session cleanup and Android restoration",
      "samsungExperimentalTitle": "Experimental Samsung desktop settings",
      "samsungUnavailable": "Available on Samsung devices only",
      "samsungExperimentalDescription":
          "Change settings hidden by the native DeX settings screen",
      "samsungSettingsTitle": "Samsung desktop settings",
      "samsungSettingsSummary": "Display, input and taskbar settings",
      "samsungRestoreSuccess": "Samsung settings restored",
      "samsungConfirmTitle": "Confirm settings access",
      "samsungPermanentWarning":
          "These settings may permanently affect Dextop and the desktop environment used normally until they are reset.",
      "samsungAcceptEnable": "Accept and enable",
      "samsungAboutSetting": "About this setting",
      "samsungRestoreEnvironment": "Restore environment",
      "samsungSettingsIntro":
          "Directly changes DeX values hidden when Samsung Settings reports no external display. Changes affect Samsung DeX and corresponding Dextop features.",
      "samsungResolution": "External resolution",
      "samsungScreenZoom": "Screen zoom (DPI)",
      "samsungFontScale": "Font size",
      "samsungScreenTimeout": "Screen timeout",
      "samsungAudioOutput": "Play audio on external display",
      "samsungDisplayOrientation": "External display rotation",
      "samsungDisplayArrangement": "Display arrangement",
      "samsungSectionInput": "Input",
      "samsungSectionDesktop": "Desktop",
      "samsungInputLockedWhileRunning":
          "Conflicting Samsung input settings cannot be changed while Dextop is running.",
      "samsungAutorunTouchpad": "Start touchpad automatically",
      "samsungTouchpadScrollDirection": "Reverse scrolling direction",
      "samsungTouchKeyboard": "Show on-screen keyboard when connected",
      "samsungKeyboardDex": "Show keyboard with physical keyboard",
      "samsungSpenInputMode": "Use S Pen as a mouse",
      "samsungThreeFingerGesture": "Three-finger gesture",
      "samsungFourFingerGesture": "Four-finger gesture",
      "samsungAutoHideTaskbar": "Automatically hide taskbar",
      "samsungDexCommandArrow": "Show command arrow",
      "samsungIncludePhoneDisplay": "Include phone display in topology",
      "samsungMirrorPhoneDisplay": "Mirror built-in display",
      "samsungReviewEnable": "Review warning and enable changes",
      "samsungSeconds15": "15 seconds",
      "samsungSeconds30": "30 seconds",
      "samsungMinute1": "1 minute",
      "samsungMinutes2": "2 minutes",
      "samsungMinutes5": "5 minutes",
      "samsungMinutes10": "10 minutes",
      "samsungMinutes20": "20 minutes",
      "samsungMinutes30": "30 minutes",
      "samsungHour1": "1 hour",
      "samsungLeft": "Left",
      "samsungRight": "Right",
      "samsungAutomatic": "Automatic",
      "samsungGestureNone": "None",
      "samsungGestureApps": "Apps",
      "samsungGestureRecents": "Recents",
      "samsungGestureNotifications": "Notifications",
      "samsungGestureQuickSettings": "Quick settings",
      "samsungHelp_resolution":
          "Resolution used by the Samsung desktop environment. It is stored separately from Dextop resolution.",
      "samsungHelp_screenZoom":
          "Changes display density (DPI) in the Samsung desktop environment.",
      "samsungHelp_fontScale":
          "Changes text scale in the Samsung desktop environment.",
      "samsungHelp_screenTimeout":
          "Time before the external desktop display turns off.",
      "samsungHelp_audioOutput": "Routes audio to the external display.",
      "samsungHelp_displayOrientation":
          "Locks external desktop display rotation.",
      "samsungHelp_displayArrangement":
          "Controls the relative arrangement of the phone and external display.",
      "samsungHelp_autorunTouchpad":
          "Starts Samsung touchpad on connection and conflicts with Dextop input.",
      "samsungHelp_touchpadScrollDirection":
          "Reverses Samsung touchpad scrolling.",
      "samsungHelp_touchKeyboard":
          "Shows the on-screen keyboard and conflicts with Dextop IME handling.",
      "samsungHelp_keyboardDex":
          "Keeps the on-screen keyboard visible with a physical keyboard and conflicts with Dextop IME handling.",
      "samsungHelp_spenInputMode": "Uses S Pen as a pointing device.",
      "samsungHelp_threeFingerGesture":
          "Samsung three-finger action; conflicts with Dextop gestures.",
      "samsungHelp_fourFingerGesture":
          "Samsung four-finger action; conflicts with Dextop multi-touch.",
      "samsungHelp_autoHideTaskbar":
          "Automatically hides the Samsung desktop taskbar.",
      "samsungHelp_dexCommandArrow": "Shows the Samsung desktop command arrow.",
      "samsungHelp_includePhoneDisplay":
          "Includes the phone display in desktop topology.",
      "samsungHelp_mirrorPhoneDisplay":
          "Mirrors the built-in display into the desktop environment.",
    },
    "zh": {
      "home": "主页",
      "settings": "设置",
      "resolution": "分辨率",
      "theme": "主题",
      "system": "跟随系统",
      "light": "浅色",
      "dark": "深色",
      "display": "显示",
      "secureDisplay": "安全显示",
      "secureDisplayDescription": "允许显示受保护的内容",
      "mirrorBackend": "显示镜像方式",
      "mirrorBackendAuto": "自动（兼容性优先）",
      "mirrorBackendAutoDescription": "使用此设备可用的最佳方式",
      "mirrorBackendWindowManager": "WindowManager",
      "mirrorBackendSurfaceControl": "SurfaceControl",
      "mirrorBackendVirtualDisplay": "VirtualDisplay",
      "updateAvailable": "有可用更新",
      "updateAvailableTitle": "GitHub 上已发布新版本！",
      "playUpdateAvailableTitle": "Google Play 上有可用更新",
      "playUpdateAvailableDescription": "您可以通过 Google Play 更新到最新版本。",
      "updateNow": "立即更新",
      "checkForUpdates": "检查更新",
      "checkingForUpdates": "正在获取更新信息",
      "updateNotChecked": "尚未获取更新信息",
      "upToDate": "已是最新版本",
      "updateCheckFailed": "无法获取更新信息",
      "currentVersion": "当前版本",
      "latestVersion": "最新版本",
      "openOnGitHub": "在 GitHub 中打开",
      "close": "关闭",
      "deviceInfo": "设备信息",
      "desktopMode": "使用的桌面模式",
      "accessibilitySettings": "无障碍设置",
      "accessibilityDescription": "打开 Dextop 服务设置",
      "appInfo": "应用信息",
      "licenses": "开源许可证",
      "licensesDescription": "查看 Flutter 和依赖库许可证",
      "landscape": "横向",
      "portrait": "纵向",
      "stopped": "已停止",
      "running": "运行中",
      "start": "启动",
      "stop": "停止",
      "customAdd": "添加自定义分辨率",
      "editResolution": "编辑分辨率",
      "add": "添加",
      "save": "保存",
      "deleteResolution": "删除此分辨率",
      "width": "宽度",
      "height": "高度",
      "protectedContent": "允许显示受保护的内容",
      "version": "版本 1.0.0",
      "setupWelcome": "欢迎使用 Dextop。",
      "setupTagline": "智能手机上的完美桌面环境。",
      "setupBegin": "开始",
      "setupPhaseTerms": "使用条款",
      "setupPhaseShizuku": "Shizuku",
      "setupPhaseDevice": "检查您的设备",
      "setupPhaseDemo": "体验操作",
      "back": "返回",
      "continueLabel": "继续",
      "done": "完成",
      "incomplete": "未完成",
      "setupSystemTitle": "使用系统级功能",
      "setupSystemDescription":
          "Dextop 使用 Shizuku 和 ADB 来控制虚拟显示、屏幕方向、输入和系统 UI 等行为。",
      "setupDisclaimer":
          "对于因设备或操作系统实现差异、系统更新、与其他应用程序冲突等而导致的任何缺陷、数据丢失或对设备功能的影响，开发者不承担任何责任。请在使用前了解内容。",
      "setupShizukuTitle": "准备 Shizuku",
      "setupShizukuDescription": "Dextop 使用 Shizuku 安全地访问系统功能。",
      "setupInstallShizuku": "安装 Shizuku",
      "setupConfigureShizuku": "设置 Shizuku",
      "setupShizukuHint": "打开 Shizuku，按照“配对”中显示的顺序进行设置，然后启动 Shizuku。",
      "setupOpenShizuku": "打开 Shizuku",
      "setupValidate": "设置完成了吗？立即验证",
      "setupDextopPermission": "授予 Dextop 权限",
      "setupInstallPlay": "从 Google Play 安装",
      "setupAllowPermission": "授予权限",
      "setupProviderChoiceTitle": "选择特权服务",
      "setupProviderChoiceDescription":
          "已同时安装 Stellar 和 Shizuku。请选择 Dextop 要使用的服务。",
      "setupUseStellar": "Stellar（推荐）",
      "setupUseShizuku": "Shizuku",
      "setupRunningAsRoot": "服务正在以 root 运行",
      "setupRootVerified": "已确认 Shizuku 正在以 root 权限运行。接下来请授予 Dextop 权限。",
      "setupRootNotRunning": "无法确认 Shizuku 正在以 root 权限运行。请使用 root 启动后重试。",
      "setupQuestionOpen": "您打开 Shizuku 了吗？",
      "setupQuestionPair": "您是否已完成“配对”下列出的所有步骤？",
      "setupQuestionStart": "您是否已在 Shizuku 中点击“启动”，并确认显示“Shizuku 正在运行”？",
      "yes": "是",
      "no": "否",
      "setupVerified": "已检查 Shizuku 设置",
      "setupVerificationFailed": "无法确认 Shizuku 的配置或启动。请完成 Shizuku 中的步骤，然后再次检查。",
      "setupPermissionCheckFailed": "无法检查 Shizuku 的权限",
      "setupDeviceTitle": "该设备上的配置",
      "model": "型号",
      "vendor": "厂商",
      "desktopUi": "桌面界面",
      "detectedResolution": "自动检测分辨率",
      "loadingLabel": "加载中…",
      "setupDeviceDescription": "此信息用于设置初始分辨率和设备特定的桌面控件。",
      "setupGestureTitle": "通过手势调出控制面板",
      "setupGestureDescription": "将三个手指同时放在下面的三个圆圈上。",
      "uiTwoFingerTap": "两根手指点击",
      "ui3FingerTap": "3 指点击",
      "ui4Divisions": "四分屏",
      "uiDextopIsReady": "Dextop 已准备就绪",
      "uiStopDextop": "停止 Dextop",
      "uiDextopCanBeRestarted": "可以恢复 Dextop",
      "uiOpenDextop": "打开 Dextop",
      "uiCreateADextopSession": "创建 Dextop 会话",
      "uiDextopWorkspaceJson": "Dextop 工作区 JSON",
      "uiPerformanceDisplayOnDextop": "在 Dextop 中显示性能浮层",
      "uiDoNotSleepWhileRunningDextop": "Dextop 运行时保持屏幕常亮",
      "uiRealTimeDisplayOfFpsMemoryPower": "实时显示 FPS、内存、功耗和电量",
      "uiCouldNotLoadJson": "无法加载 JSON",
      "uiSecureSettingsPermission": "安全设置权限",
      "uiAllowShizukuPermissions": "授予 Shizuku 权限",
      "uiInstallShizuku": "安装 Shizuku",
      "uiCheckingShizukuConnection": "检查 Shizuku 连接",
      "uiShizukuConnection": "Shizuku 连接",
      "uiCopy": "的副本",
      "uiOthers": "其他",
      "uiAccessibilityOverlay": "无障碍浮层",
      "uiAccessibilityServices": "无障碍服务",
      "uiAppNotFound": "找不到应用程序",
      "uiAppsAndWorkspace": "应用程序和工作区",
      "uiLaunchTheAppAndConfigureYourWorkspace": "启动应用并配置工作区",
      "uiRestartTheApp": "重启应用",
      "uiSearchApp": "搜索应用",
      "uiAppMemory": "应用内存",
      "uiAppLauncher": "应用程序启动器",
      "uiAppLauncherSettings": "应用程序启动器设置",
      "uiAppLaunchFunction": "应用程序启动功能",
      "uiImport": "导入",
      "uiExport": "导出",
      "uiCursor": "光标",
      "uiCancel": "取消",
      "uiQuickSettingsTile": "快速设置图块",
      "uiGesture": "手势",
      "uiSecondaryIme": "辅助输入法",
      "uiSecureDisplayFoldable": "安全显示、镜像方式、可折叠设备",
      "uiSecurity": "安全",
      "uiTap": "点击",
      "uiTapPressAndHoldMultiFingerOperation": "点击、长按和多指操作",
      "uiOpenAppOnDesktop": "在桌面上打开应用程序",
      "uiDesktopMode": "桌面模式",
      "uiDesktopFeatures": "桌面功能",
      "uiTrackpad": "触控板",
      "uiDrag": "拖动",
      "uiBattery": "电池",
      "uiPerformance": "性能",
      "uiPerformanceCompatibility": "性能、兼容性",
      "uiItSupportsMultiTouchAndTheThree": "启用多点触控后，三指手势将改为从屏幕左边缘滑动。",
      "uiMainLarge2Sub": "主窗口大 + 两个副窗口",
      "uiMainLeft": "主窗口（左）",
      "uiLayout": "布局",
      "uiWorkSpace": "工作空间",
      "uiCopiedWorkspaceJsonToClipboard": "将工作区 JSON 复制到剪贴板",
      "uiImportWorkspace": "导入工作区",
      "uiSaveWorkspace": "保存工作区",
      "uiDeleteWorkspace": "删除工作区",
      "uiEditWorkspace": "编辑工作区",
      "uiUp": "上移",
      "uiDividedIntoUpperAndLowerParts": "上下分屏",
      "uiUpperHalf": "上半部分",
      "uiMoveDown": "向下移动",
      "uiLowerHalf": "下半部分",
      "uiCenter": "居中",
      "uiCompatibilityDiagnosis": "兼容性诊断",
      "uiVirtualDisplayCreation": "虚拟显示创建",
      "uiOpenASavedAppConfiguration": "打开保存的应用程序配置",
      "uiNoSavedWorkspaces": "没有保存的工作区",
      "uiInputAndGestures": "输入和手势",
      "uiInputMode": "输入方式",
      "uiCancelFullScreen": "退出全屏",
      "uiReDiagnosis": "重新运行诊断",
      "uiRestart": "恢复",
      "uiAvailableMemory": "可用内存",
      "uiDelete": "删除",
      "uiYouCanRestoreYourPreviousSession": "您可以恢复之前的会话",
      "uiRight": "右侧",
      "uiRight13": "右1/3",
      "uiRight23": "右2/3",
      "uiRightClick": "右键单击",
      "uiUpperRight": "右上",
      "uiLowerRight": "右下",
      "uiRightHalf": "右半屏",
      "uiName": "名称",
      "uiLargeScreenFoldable": "大屏/可折叠",
      "uiActualFps": "实际帧率",
      "uiExperimentalMultiTouch": "实验性多点触控",
      "uiExperimentalFeatures": "实验性功能",
      "uiLeft": "左侧",
      "uiLeft13": "左1/3",
      "uiLeft13Right23": "左1/3・右2/3",
      "uiLeft23": "左 2/3",
      "uiLeft23Right13": "左2/3・右1/3",
      "uiLeftCenterRight": "左/中/右",
      "uiUpperLeft": "左上",
      "uiUpperLeftUpperRightLowerHalf": "左上、右上、下半部",
      "uiLowerLeft": "左下",
      "uiLeftHalf": "左半屏",
      "uiDividedIntoLeftAndRight": "左右分屏",
      "uiSwipeRightWithThreeFingersFromThe": "用三个手指从左边缘向右滑动",
      "uiRecoverySession": "恢复会话",
      "uiEstimatedPowerConsumption": "预计功耗",
      "uiOperationOverlay": "操作浮层",
      "uiShowActionOverlay": "显示操作浮层",
      "uiOperationMenu": "控制菜单",
      "uiThereIsAnExistingSession": "已有会话",
      "uiSaveConfiguration": "保存配置",
      "uiRestorePrivileges": "恢复权限",
      "uiChangeToHorizontalHold": "切换为横向",
      "uiPreparationIsRequired": "需要完成设置",
      "uiPhysicalKeyboard": "物理键盘",
      "uiPhysicalMouse": "物理鼠标",
      "uiConditionAndDiagnosis": "状态与诊断",
      "uiPreventsTheScreenFromTurningOffAutomatically": "防止屏幕自动关闭",
      "uiDestruction": "丢弃",
      "uiTerminalAndPermissions": "设备与权限",
      "uiDeviceInformationDesktopModeAccessibility": "设备信息、桌面模式、辅助功能",
      "uiTerminalResolution": "设备分辨率",
      "uiEnd": "结束",
      "uiTerminationProcessingCompletedSuccessfully": "会话已正常结束。",
      "uiEdit": "编辑",
      "uiChangeToPortraitOrientation": "切换为纵向",
      "uiVerticalHorizontalSwitching": "横向/纵向切换",
      "uiDisplayOptimization": "显示优化",
      "uiDisplayRefreshRate": "显示刷新率",
      "uiReproduction": "复制",
      "uiManageLaunchedAppsAndConfigurations": "管理要启动的应用及其布局",
      "uiCouldNotStart": "无法启动",
      "uiLongPress": "长按",
      "uiAutomaticallyUsesMeasuredResolutionForOpenAnd": "自动使用测量的打开和关闭状态分辨率",
      "uiStart": "开始",
      "uiAutomaticSwitchingAccordingToOpenClosedState": "根据开/关状态自动切换",
      "uiOpeningQuote": "“",
      "uiDeleteWorkspaceQuestionSuffix": "”？",
      "uiAbnormalSessionWarning": "会话在异常状态下结束。\n部分 Android 系统功能可能仍处于禁用状态。",
      "uiChecking": "正在检查",
      "uiIdle": "空闲",
      "uiAvailable": "Available",
      "uiUnavailable": "Unavailable",
      "appName": "Dextop",
      "uiAndroid": "Android",
      "uiGitHub": "GitHub",
      "uiGitHubRepository": "NarYuki/Dextop",
      "diagnosticLog": "运行日志和设备诊断",
      "diagnosticLogDescription": "查看应用日志、功能检测和详细设备规格",
      "loadDiagnosticLog": "加载诊断报告",
      "copyDiagnosticLog": "复制",
      "shareDiagnosticLog": "分享",
      "clearDiagnosticLog": "清除日志",
      "deviceReport": "设备运行报告",
      "uiCpuTemperature": "CPU 温度",
      "deviceReportDescription": "通过电子邮件报告设备和功能兼容性",
      "deviceReportIntro": "设备信息将自动收集。请选择各项功能的运行结果。",
      "reportWorking": "可用",
      "reportNotWorking": "不可用",
      "reportUntested": "未测试",
      "reportOverall": "总体状态",
      "reportNotes": "其他备注",
      "sendDeviceReport": "通过邮件发送报告",
      "reportEmailUnavailable": "无法打开邮件应用",
      "reportTemplateTitle": "Dextop 设备运行报告",
      "reportNoNotes": "无",
      "reportNoSessionLog": "尚未记录已完成的Dextop会话日志。",
      "reportFeatureStartup": "应用启动与设备检测",
      "reportFeatureSession": "Dextop 会话启动",
      "reportFeatureVirtualDisplay": "VirtualDisplay 镜像",
      "reportFeatureWindowManager": "WindowManager 镜像",
      "reportFeatureSurfaceControl": "SurfaceControl 镜像",
      "reportFeatureLandscape": "横屏模式",
      "reportFeaturePortrait": "竖屏模式",
      "reportFeatureSecureDisplay": "安全显示",
      "reportFeatureLauncher": "应用启动器与自由窗口",
      "reportFeatureWorkspace": "工作区保存与恢复",
      "reportFeatureCursor": "光标与触控板输入",
      "reportFeatureDirectTouch": "直接触控输入",
      "reportFeatureMultiTouch": "多点触控滚动与双指缩放",
      "reportFeatureGesture": "三指浮层手势",
      "reportFeatureMouse": "物理鼠标",
      "reportFeatureKeyboard": "物理键盘",
      "reportFeatureRouting": "物理鼠标与键盘显示路由",
      "reportFeatureFoldable": "折叠设备自动分辨率",
      "reportFeaturePerformance": "性能浮层",
      "reportFeatureCleanup": "会话清理与 Android 状态恢复",
      "samsungExperimentalTitle": "实验性 Samsung 桌面设置",
      "samsungUnavailable": "仅可在 Samsung 设备上使用",
      "samsungExperimentalDescription": "从 Dextop 更改原生 DeX 设置中隐藏的项目",
      "samsungSettingsTitle": "Samsung 桌面设置",
      "samsungSettingsSummary": "显示、输入和任务栏设置",
      "samsungRestoreSuccess": "已恢复 Samsung 设置",
      "samsungConfirmTitle": "确认更改设置",
      "samsungPermanentWarning": "这些项目可能会永久影响 Dextop 和日常使用的桌面环境，直到重置为止。",
      "samsungAcceptEnable": "同意并启用",
      "samsungAboutSetting": "关于此设置",
      "samsungRestoreEnvironment": "恢复环境",
      "samsungSettingsIntro":
          "直接更改 Samsung 设置因未检测到外接显示器而隐藏的 DeX 值。更改会影响 Samsung DeX 及对应的 Dextop 功能。",
      "samsungResolution": "外接屏幕分辨率",
      "samsungScreenZoom": "屏幕缩放 (DPI)",
      "samsungFontScale": "字体大小",
      "samsungScreenTimeout": "屏幕超时",
      "samsungAudioOutput": "从外接屏幕输出音频",
      "samsungDisplayOrientation": "外接屏幕旋转",
      "samsungDisplayArrangement": "屏幕排列",
      "samsungSectionInput": "输入",
      "samsungSectionDesktop": "桌面",
      "samsungInputLockedWhileRunning": "Dextop 运行时无法更改有冲突的 Samsung 输入设置。",
      "samsungAutorunTouchpad": "自动启动触控板",
      "samsungTouchpadScrollDirection": "反转滚动方向",
      "samsungTouchKeyboard": "连接时显示屏幕键盘",
      "samsungKeyboardDex": "使用物理键盘时仍显示键盘",
      "samsungSpenInputMode": "将 S Pen 用作鼠标",
      "samsungThreeFingerGesture": "三指手势",
      "samsungFourFingerGesture": "四指手势",
      "samsungAutoHideTaskbar": "自动隐藏任务栏",
      "samsungDexCommandArrow": "显示命令箭头",
      "samsungIncludePhoneDisplay": "将手机屏幕加入显示拓扑",
      "samsungMirrorPhoneDisplay": "镜像内置屏幕",
      "samsungReviewEnable": "查看警告并启用更改",
      "samsungSeconds15": "15 秒",
      "samsungSeconds30": "30 秒",
      "samsungMinute1": "1 分钟",
      "samsungMinutes2": "2 分钟",
      "samsungMinutes5": "5 分钟",
      "samsungMinutes10": "10 分钟",
      "samsungMinutes20": "20 分钟",
      "samsungMinutes30": "30 分钟",
      "samsungHour1": "1 小时",
      "samsungLeft": "左",
      "samsungRight": "右",
      "samsungAutomatic": "自动",
      "samsungGestureNone": "无",
      "samsungGestureApps": "应用列表",
      "samsungGestureRecents": "最近任务",
      "samsungGestureNotifications": "通知",
      "samsungGestureQuickSettings": "快捷设置",
      "samsungHelp_resolution": "Samsung 桌面环境使用的外接屏幕分辨率，与 Dextop 分辨率分开保存。",
      "samsungHelp_screenZoom": "更改 Samsung 桌面环境的显示密度 (DPI)。",
      "samsungHelp_fontScale": "更改 Samsung 桌面环境的文字缩放。",
      "samsungHelp_screenTimeout": "外接桌面屏幕关闭前的等待时间。",
      "samsungHelp_audioOutput": "将音频输出切换到外接屏幕。",
      "samsungHelp_displayOrientation": "锁定外接桌面屏幕的旋转方向。",
      "samsungHelp_displayArrangement": "指定手机屏幕与外接屏幕的相对位置。",
      "samsungHelp_autorunTouchpad": "连接时自动显示 Samsung 触控板，会与 Dextop 输入冲突。",
      "samsungHelp_touchpadScrollDirection": "反转 Samsung 触控板的滚动方向。",
      "samsungHelp_touchKeyboard": "显示屏幕键盘，会与 Dextop IME 控制冲突。",
      "samsungHelp_keyboardDex": "连接物理键盘时仍显示屏幕键盘，会与 Dextop IME 控制冲突。",
      "samsungHelp_spenInputMode": "将 S Pen 用作指针设备。",
      "samsungHelp_threeFingerGesture": "Samsung 三指操作，会与 Dextop 手势冲突。",
      "samsungHelp_fourFingerGesture": "Samsung 四指操作，会与 Dextop 多点触控冲突。",
      "samsungHelp_autoHideTaskbar": "自动隐藏 Samsung 桌面任务栏。",
      "samsungHelp_dexCommandArrow": "显示 Samsung 桌面命令箭头。",
      "samsungHelp_includePhoneDisplay": "将手机屏幕加入桌面显示拓扑。",
      "samsungHelp_mirrorPhoneDisplay": "将内置屏幕镜像到桌面环境。",
    },
    "ko": {
      "home": "홈",
      "settings": "설정",
      "resolution": "해상도",
      "theme": "테마",
      "system": "시스템",
      "light": "라이트",
      "dark": "다크",
      "display": "디스플레이",
      "secureDisplay": "보안 표시",
      "secureDisplayDescription": "보호된 콘텐츠 표시를 허용합니다",
      "mirrorBackend": "디스플레이 미러링 방식",
      "mirrorBackendAuto": "자동(호환성 우선)",
      "mirrorBackendAutoDescription": "이 기기에서 사용 가능한 최적의 방식을 사용합니다",
      "mirrorBackendWindowManager": "WindowManager",
      "mirrorBackendSurfaceControl": "SurfaceControl",
      "mirrorBackendVirtualDisplay": "VirtualDisplay",
      "updateAvailable": "업데이트가 있습니다",
      "updateAvailableTitle": "GitHub에 새 릴리스가 공개되었습니다!",
      "playUpdateAvailableTitle": "Google Play에 업데이트가 있습니다",
      "playUpdateAvailableDescription": "Google Play에서 최신 버전으로 업데이트할 수 있습니다.",
      "updateNow": "지금 업데이트",
      "checkForUpdates": "업데이트 확인",
      "checkingForUpdates": "업데이트 정보를 가져오는 중입니다",
      "updateNotChecked": "업데이트 정보를 아직 가져오지 않았습니다",
      "upToDate": "최신 버전입니다",
      "updateCheckFailed": "업데이트 정보를 가져올 수 없습니다",
      "currentVersion": "현재 버전",
      "latestVersion": "최신 버전",
      "openOnGitHub": "GitHub에서 열기",
      "close": "닫기",
      "deviceInfo": "기기 정보",
      "desktopMode": "사용할 데스크톱 모드",
      "accessibilitySettings": "접근성 설정",
      "accessibilityDescription": "Dextop 서비스 설정을 엽니다",
      "appInfo": "앱 정보",
      "licenses": "오픈 소스 라이선스",
      "licensesDescription": "Flutter 및 사용 라이브러리 라이선스 표시",
      "landscape": "가로",
      "portrait": "세로",
      "stopped": "중지됨",
      "running": "실행 중",
      "start": "시작",
      "stop": "중지",
      "customAdd": "사용자 지정 해상도 추가",
      "editResolution": "해상도 편집",
      "add": "추가",
      "save": "저장",
      "deleteResolution": "이 해상도 삭제",
      "width": "너비",
      "height": "높이",
      "protectedContent": "보호된 콘텐츠 표시를 허용합니다",
      "version": "버전 1.0.0",
      "setupWelcome": "Dextop에 오신 것을 환영합니다.",
      "setupTagline": "스마트폰 하나로 완벽한 데스크톱 환경을.",
      "setupBegin": "시작하기",
      "setupPhaseTerms": "이용에 있어서",
      "setupPhaseShizuku": "Shizuku",
      "setupPhaseDevice": "기기 확인",
      "setupPhaseDemo": "조작 체험",
      "back": "뒤로",
      "continueLabel": "계속",
      "done": "완료",
      "incomplete": "미완료",
      "setupSystemTitle": "시스템 기능을 이용",
      "setupSystemDescription":
          "Dextop은 Shizuku와 ADB를 사용하여 가상 디스플레이, 화면 방향, 입력, 시스템 UI 등의 동작을 제어합니다.",
      "setupDisclaimer":
          "단말기와 OS의 구현 차이, 시스템 업데이트, 다른 앱과의 충돌 등으로 인한 문제, 데이터 손실, 단말기 기능에 미치는 영향에 대해서는 개발자는 책임을 지지 않습니다. 내용을 이해한 후 사용하십시오.",
      "setupShizukuTitle": "Shizuku 준비",
      "setupShizukuDescription":
          "Dextop이 시스템 기능에 안전하게 액세스하기 위해 Shizuku를 사용합니다.",
      "setupInstallShizuku": "Shizuku 설치",
      "setupConfigureShizuku": "Shizuku 설정",
      "setupShizukuHint":
          "Shizuku를 열고 \"페어링\"에 나타나는 순서에 따라 설정하고 Shizuku를 시작하십시오.",
      "setupOpenShizuku": "Shizuku 열기",
      "setupValidate": "설정이 완료되었습니까? 유효성 확인",
      "setupDextopPermission": "Dextop에 대한 권한",
      "setupInstallPlay": "Google Play에서 설치",
      "setupAllowPermission": "권한 부여",
      "setupProviderChoiceTitle": "권한 서비스 선택",
      "setupProviderChoiceDescription":
          "Stellar와 Shizuku가 모두 설치되어 있습니다. Dextop에서 사용할 서비스를 선택하세요.",
      "setupUseStellar": "Stellar(권장)",
      "setupUseShizuku": "Shizuku",
      "setupRunningAsRoot": "서비스를 root로 실행 중입니다",
      "setupRootVerified":
          "Shizuku가 root 권한으로 실행 중임을 확인했습니다. 다음으로 Dextop 권한을 부여하세요.",
      "setupRootNotRunning":
          "Shizuku가 root 권한으로 실행 중인지 확인할 수 없습니다. root로 시작한 후 다시 시도하세요.",
      "setupQuestionOpen": "Shizuku를 열었나요?",
      "setupQuestionPair": "'페어링'에 표시된 모든 단계를 완료했습니까?",
      "setupQuestionStart":
          "Shizuku에서 \"시작\"을 누르고 \"Shizuku가 실행 중입니다.\"라고 표시됩니까?",
      "yes": "예",
      "no": "아니오",
      "setupVerified": "Shizuku 설정을 확인했습니다",
      "setupVerificationFailed":
          "Shizuku 설정 또는 시작을 확인할 수 없습니다. Shizuku의 절차를 완료한 후 다시 확인하십시오.",
      "setupPermissionCheckFailed": "Shizuku의 권한을 확인할 수 없습니다.",
      "setupDeviceTitle": "이 단말기의 구성",
      "model": "기종",
      "vendor": "벤더",
      "desktopUi": "데스크톱 UI",
      "detectedResolution": "자동 감지 해상도",
      "loadingLabel": "불러오는 중…",
      "setupDeviceDescription": "이 정보를 바탕으로 초기 해상도와 기기별 데스크톱 제어를 설정합니다.",
      "setupGestureTitle": "제스처로 조작 패널 호출",
      "setupGestureDescription": "아래의 3개의 원에 3개의 손가락을 동시에 놓으십시오.",
      "uiTwoFingerTap": "두 손가락 탭",
      "ui3FingerTap": "세 손가락 탭",
      "ui4Divisions": "4분할",
      "uiDextopIsReady": "Dextop 준비됨",
      "uiStopDextop": "Dextop 중지",
      "uiDextopCanBeRestarted": "Dextop을 재개할 수 있습니다.",
      "uiOpenDextop": "Dextop 열기",
      "uiCreateADextopSession": "Dextop 세션 만들기",
      "uiDextopWorkspaceJson": "Dextop 작업 공간 JSON",
      "uiPerformanceDisplayOnDextop": "Dextop에 성능 오버레이 표시",
      "uiDoNotSleepWhileRunningDextop": "Dextop 실행 중 화면 켜짐 유지",
      "uiRealTimeDisplayOfFpsMemoryPower": "FPS, 메모리, 전력 소비, 배터리 실시간 표시",
      "uiCouldNotLoadJson": "JSON을 로드할 수 없습니다.",
      "uiSecureSettingsPermission": "Secure Settings 권한",
      "uiAllowShizukuPermissions": "Shizuku의 권한 부여",
      "uiInstallShizuku": "Shizuku 설치",
      "uiCheckingShizukuConnection": "Shizuku 연결 확인 중",
      "uiShizukuConnection": "Shizuku 연결",
      "uiCopy": "사본",
      "uiOthers": "기타",
      "uiAccessibilityOverlay": "접근성 오버레이",
      "uiAccessibilityServices": "내게 필요한 옵션 서비스",
      "uiAppNotFound": "앱을 찾을 수 없음",
      "uiAppsAndWorkspace": "앱 및 작업공간",
      "uiLaunchTheAppAndConfigureYourWorkspace": "앱 시작 및 작업 공간 구성",
      "uiRestartTheApp": "앱 다시 시작",
      "uiSearchApp": "앱 검색",
      "uiAppMemory": "앱 메모리",
      "uiAppLauncher": "앱 런처",
      "uiAppLauncherSettings": "앱 런처 설정",
      "uiAppLaunchFunction": "앱 시작 기능",
      "uiImport": "가져오기",
      "uiExport": "내보내기",
      "uiCursor": "커서",
      "uiCancel": "취소",
      "uiQuickSettingsTile": "빠른 설정 타일",
      "uiGesture": "제스처",
      "uiSecondaryIme": "보조 IME",
      "uiSecureDisplayFoldable": "보안 디스플레이, 미러링 방식, Foldable",
      "uiSecurity": "보안",
      "uiTap": "탭",
      "uiTapPressAndHoldMultiFingerOperation": "탭, 길게 누르기, 여러 손가락 조작",
      "uiOpenAppOnDesktop": "데스크톱에서 앱 열기",
      "uiDesktopMode": "데스크톱 모드",
      "uiDesktopFeatures": "데스크톱 기능",
      "uiTrackpad": "트랙패드",
      "uiDrag": "드래그",
      "uiBattery": "배터리",
      "uiPerformance": "공연",
      "uiPerformanceCompatibility": "성능 및 호환성",
      "uiItSupportsMultiTouchAndTheThree":
          "멀티터치를 활성화하면 세 손가락 제스처가 화면 왼쪽 가장자리 스와이프로 변경됩니다.",
      "uiMainLarge2Sub": "큰 메인 창 + 보조 창 2개",
      "uiMainLeft": "메인(왼쪽)",
      "uiLayout": "레이아웃",
      "uiWorkSpace": "작업 공간",
      "uiCopiedWorkspaceJsonToClipboard": "작업 공간 JSON을 클립 보드에 복사했습니다.",
      "uiImportWorkspace": "작업 공간 가져오기",
      "uiSaveWorkspace": "작업 공간 저장",
      "uiDeleteWorkspace": "작업공간 삭제",
      "uiEditWorkspace": "작업공간 편집",
      "uiUp": "위로",
      "uiDividedIntoUpperAndLowerParts": "상하 2분할",
      "uiUpperHalf": "상반부",
      "uiMoveDown": "아래로 이동",
      "uiLowerHalf": "하반부",
      "uiCenter": "중앙",
      "uiCompatibilityDiagnosis": "호환성 진단",
      "uiVirtualDisplayCreation": "가상 디스플레이 생성",
      "uiOpenASavedAppConfiguration": "저장된 앱 구성 열기",
      "uiNoSavedWorkspaces": "저장된 작업공간 없음",
      "uiInputAndGestures": "입력과 제스처",
      "uiInputMode": "입력 모드",
      "uiCancelFullScreen": "전체 화면 해제",
      "uiReDiagnosis": "재진단",
      "uiRestart": "재개",
      "uiAvailableMemory": "사용 가능한 메모리",
      "uiDelete": "삭제",
      "uiYouCanRestoreYourPreviousSession": "마지막 세션을 복구할 수 있습니다.",
      "uiRight": "오른쪽",
      "uiRight13": "오른쪽 1/3",
      "uiRight23": "오른쪽 2/3",
      "uiRightClick": "오른쪽 클릭",
      "uiUpperRight": "오른쪽 상단",
      "uiLowerRight": "오른쪽 하단",
      "uiRightHalf": "오른쪽 절반",
      "uiName": "이름",
      "uiLargeScreenFoldable": "큰 화면 · Foldable",
      "uiActualFps": "실측 FPS",
      "uiExperimentalMultiTouch": "실험적인 멀티 터치",
      "uiExperimentalFeatures": "실험 기능",
      "uiLeft": "왼쪽",
      "uiLeft13": "왼쪽 1/3",
      "uiLeft13Right23": "왼쪽 1/3 · 오른쪽 2/3",
      "uiLeft23": "왼쪽 2/3",
      "uiLeft23Right13": "왼쪽 2/3 · 오른쪽 1/3",
      "uiLeftCenterRight": "왼쪽, 중앙, 오른쪽",
      "uiUpperLeft": "왼쪽 상단",
      "uiUpperLeftUpperRightLowerHalf": "좌상, 우상, 하반부",
      "uiLowerLeft": "왼쪽 하단",
      "uiLeftHalf": "왼쪽 절반",
      "uiDividedIntoLeftAndRight": "좌우 2분할",
      "uiSwipeRightWithThreeFingersFromThe": "왼쪽 끝에서 3 손가락으로 오른쪽으로 스 와이프",
      "uiRecoverySession": "복구 세션",
      "uiEstimatedPowerConsumption": "예상 소비 전력",
      "uiOperationOverlay": "조작 오버레이",
      "uiShowActionOverlay": "조작 오버레이 표시",
      "uiOperationMenu": "조작 메뉴",
      "uiThereIsAnExistingSession": "기존 세션이 있습니다.",
      "uiSaveConfiguration": "구성 저장",
      "uiRestorePrivileges": "권한 복구",
      "uiChangeToHorizontalHold": "가로로 변경",
      "uiPreparationIsRequired": "준비가 필요",
      "uiPhysicalKeyboard": "물리적 키보드",
      "uiPhysicalMouse": "물리 마우스",
      "uiConditionAndDiagnosis": "상태 및 진단",
      "uiPreventsTheScreenFromTurningOffAutomatically": "화면 자동 꺼짐 방지",
      "uiDestruction": "삭제",
      "uiTerminalAndPermissions": "터미널 및 권한",
      "uiDeviceInformationDesktopModeAccessibility": "터미널 정보, 데스크톱 모드, 접근성",
      "uiTerminalResolution": "터미널 해상도",
      "uiEnd": "종료",
      "uiTerminationProcessingCompletedSuccessfully": "세션이 정상적으로 종료되었습니다.",
      "uiEdit": "편집",
      "uiChangeToPortraitOrientation": "세로로 변경",
      "uiVerticalHorizontalSwitching": "종횡 전환",
      "uiDisplayOptimization": "디스플레이 최적화",
      "uiDisplayRefreshRate": "디스플레이 새로고침 속도",
      "uiReproduction": "복사본 만들기",
      "uiManageLaunchedAppsAndConfigurations": "시작할 앱 및 구성 관리",
      "uiCouldNotStart": "시작할 수 없습니다.",
      "uiLongPress": "길게 누르기",
      "uiAutomaticallyUsesMeasuredResolutionForOpenAnd":
          "열린 상태와 닫힌 상태의 실측 해상도 자동 사용",
      "uiStart": "시작",
      "uiAutomaticSwitchingAccordingToOpenClosedState": "개폐 상태에 따라 자동 전환",
      "uiOpeningQuote": "“",
      "uiDeleteWorkspaceQuestionSuffix": "” 작업 공간을 삭제하시겠습니까?",
      "uiAbnormalSessionWarning":
          "세션이 비정상 상태로 종료되었습니다.\n일부 Android 시스템 기능이 여전히 비활성화되어 있을 수 있습니다.",
      "uiChecking": "확인 중",
      "uiIdle": "대기 중",
      "uiAvailable": "Available",
      "uiUnavailable": "Unavailable",
      "appName": "Dextop",
      "uiAndroid": "Android",
      "uiGitHub": "GitHub",
      "uiGitHubRepository": "NarYuki/Dextop",
      "diagnosticLog": "작동 로그 및 기기 진단",
      "diagnosticLogDescription": "앱 로그, 기능 감지 및 상세 기기 사양을 표시합니다",
      "loadDiagnosticLog": "진단 보고서 불러오기",
      "copyDiagnosticLog": "복사",
      "shareDiagnosticLog": "공유",
      "clearDiagnosticLog": "로그 지우기",
      "deviceReport": "기기 작동 보고",
      "uiCpuTemperature": "CPU 온도",
      "deviceReportDescription": "기기 및 기능 호환성을 이메일로 보고",
      "deviceReportIntro": "기기 정보는 자동으로 수집됩니다. 각 기능의 결과를 선택하세요.",
      "reportWorking": "작동함",
      "reportNotWorking": "작동 안 함",
      "reportUntested": "미확인",
      "reportOverall": "전체 상태",
      "reportNotes": "기타 특이사항",
      "sendDeviceReport": "이메일로 보고서 보내기",
      "reportEmailUnavailable": "이메일 앱을 열 수 없습니다",
      "reportTemplateTitle": "Dextop 기기 작동 보고",
      "reportNoNotes": "없음",
      "reportNoSessionLog": "완료된 Dextop 세션 로그가 아직 없습니다.",
      "reportFeatureStartup": "앱 시작 및 기기 감지",
      "reportFeatureSession": "Dextop 세션 시작",
      "reportFeatureVirtualDisplay": "VirtualDisplay 미러링",
      "reportFeatureWindowManager": "WindowManager 미러링",
      "reportFeatureSurfaceControl": "SurfaceControl 미러링",
      "reportFeatureLandscape": "가로 모드",
      "reportFeaturePortrait": "세로 모드",
      "reportFeatureSecureDisplay": "보안 디스플레이",
      "reportFeatureLauncher": "앱 런처 및 자유 형식 창",
      "reportFeatureWorkspace": "작업 공간 저장 및 복원",
      "reportFeatureCursor": "커서 및 터치패드 입력",
      "reportFeatureDirectTouch": "직접 터치 입력",
      "reportFeatureMultiTouch": "멀티터치 스크롤 및 핀치 줌",
      "reportFeatureGesture": "세 손가락 오버레이 제스처",
      "reportFeatureMouse": "물리 마우스",
      "reportFeatureKeyboard": "물리 키보드",
      "reportFeatureRouting": "물리 마우스 및 키보드 디스플레이 라우팅",
      "reportFeatureFoldable": "폴더블 자동 해상도",
      "reportFeaturePerformance": "성능 오버레이",
      "reportFeatureCleanup": "세션 정리 및 Android 상태 복원",
      "samsungExperimentalTitle": "실험적 Samsung 데스크톱 설정",
      "samsungUnavailable": "Samsung 기기에서만 사용할 수 있습니다",
      "samsungExperimentalDescription": "기본 DeX 설정 화면에서 숨겨진 항목을 Dextop에서 변경합니다",
      "samsungSettingsTitle": "Samsung 데스크톱 설정",
      "samsungSettingsSummary": "화면, 입력 및 작업 표시줄 설정",
      "samsungRestoreSuccess": "Samsung 설정을 복원했습니다",
      "samsungConfirmTitle": "설정 변경 확인",
      "samsungPermanentWarning":
          "이 항목은 초기화할 때까지 Dextop 및 평소 사용하는 데스크톱 환경에 영구적인 영향을 줄 수 있습니다.",
      "samsungAcceptEnable": "동의하고 활성화",
      "samsungAboutSetting": "이 설정 정보",
      "samsungRestoreEnvironment": "환경 복원",
      "samsungSettingsIntro":
          "Samsung 설정이 외부 디스플레이 미연결 상태에서 숨기는 DeX 값을 직접 변경합니다. 변경 사항은 Samsung DeX 및 해당 Dextop 기능에 적용됩니다.",
      "samsungResolution": "외부 화면 해상도",
      "samsungScreenZoom": "화면 확대/축소(DPI)",
      "samsungFontScale": "글자 크기",
      "samsungScreenTimeout": "화면 시간 제한",
      "samsungAudioOutput": "외부 화면으로 오디오 출력",
      "samsungDisplayOrientation": "외부 화면 회전",
      "samsungDisplayArrangement": "화면 배치",
      "samsungSectionInput": "입력",
      "samsungSectionDesktop": "데스크톱",
      "samsungInputLockedWhileRunning":
          "Dextop 실행 중에는 충돌하는 Samsung 입력 설정을 변경할 수 없습니다.",
      "samsungAutorunTouchpad": "터치패드 자동 실행",
      "samsungTouchpadScrollDirection": "스크롤 방향 반전",
      "samsungTouchKeyboard": "연결 시 화면 키보드 표시",
      "samsungKeyboardDex": "물리 키보드 사용 중에도 키보드 표시",
      "samsungSpenInputMode": "S Pen을 마우스로 사용",
      "samsungThreeFingerGesture": "세 손가락 제스처",
      "samsungFourFingerGesture": "네 손가락 제스처",
      "samsungAutoHideTaskbar": "작업 표시줄 자동 숨기기",
      "samsungDexCommandArrow": "명령 화살표 표시",
      "samsungIncludePhoneDisplay": "휴대전화 화면을 디스플레이 토폴로지에 포함",
      "samsungMirrorPhoneDisplay": "내장 화면 미러링",
      "samsungReviewEnable": "경고를 확인하고 설정 변경 활성화",
      "samsungSeconds15": "15초",
      "samsungSeconds30": "30초",
      "samsungMinute1": "1분",
      "samsungMinutes2": "2분",
      "samsungMinutes5": "5분",
      "samsungMinutes10": "10분",
      "samsungMinutes20": "20분",
      "samsungMinutes30": "30분",
      "samsungHour1": "1시간",
      "samsungLeft": "왼쪽",
      "samsungRight": "오른쪽",
      "samsungAutomatic": "자동",
      "samsungGestureNone": "없음",
      "samsungGestureApps": "앱 목록",
      "samsungGestureRecents": "최근 앱",
      "samsungGestureNotifications": "알림",
      "samsungGestureQuickSettings": "빠른 설정",
      "samsungHelp_resolution":
          "Samsung 데스크톱 환경에서 사용하는 외부 화면 해상도이며 Dextop 해상도와 별도로 저장됩니다.",
      "samsungHelp_screenZoom": "Samsung 데스크톱 환경의 표시 밀도(DPI)를 변경합니다.",
      "samsungHelp_fontScale": "Samsung 데스크톱 환경의 글자 배율을 변경합니다.",
      "samsungHelp_screenTimeout": "외부 데스크톱 화면이 꺼질 때까지의 시간입니다.",
      "samsungHelp_audioOutput": "오디오 출력을 외부 화면으로 전환합니다.",
      "samsungHelp_displayOrientation": "외부 데스크톱 화면의 회전 방향을 고정합니다.",
      "samsungHelp_displayArrangement": "휴대전화와 외부 화면의 상대 위치를 지정합니다.",
      "samsungHelp_autorunTouchpad":
          "연결 시 Samsung 터치패드를 자동 표시하며 Dextop 입력과 충돌합니다.",
      "samsungHelp_touchpadScrollDirection": "Samsung 터치패드의 스크롤 방향을 반전합니다.",
      "samsungHelp_touchKeyboard": "화면 키보드를 표시하며 Dextop IME 제어와 충돌합니다.",
      "samsungHelp_keyboardDex":
          "물리 키보드 연결 중에도 화면 키보드를 표시하며 Dextop IME 제어와 충돌합니다.",
      "samsungHelp_spenInputMode": "S Pen을 포인팅 장치로 사용합니다.",
      "samsungHelp_threeFingerGesture": "Samsung 세 손가락 동작이며 Dextop 제스처와 충돌합니다.",
      "samsungHelp_fourFingerGesture": "Samsung 네 손가락 동작이며 Dextop 멀티터치와 충돌합니다.",
      "samsungHelp_autoHideTaskbar": "Samsung 데스크톱 작업 표시줄을 자동으로 숨깁니다.",
      "samsungHelp_dexCommandArrow": "Samsung 데스크톱 명령 화살표를 표시합니다.",
      "samsungHelp_includePhoneDisplay": "휴대전화 화면을 데스크톱 디스플레이 토폴로지에 포함합니다.",
      "samsungHelp_mirrorPhoneDisplay": "내장 화면을 데스크톱 환경에 미러링합니다.",
    },
    "ru": {
      "home": "Главная",
      "settings": "Настройки",
      "resolution": "Разрешение",
      "theme": "Тема",
      "system": "Системная",
      "light": "Светлая",
      "dark": "Тёмная",
      "display": "Экран",
      "secureDisplay": "Защищённый экран",
      "secureDisplayDescription": "Разрешить показ защищённого содержимого",
      "mirrorBackend": "Способ зеркалирования дисплея",
      "mirrorBackendAuto": "Автоматически (совместимость)",
      "mirrorBackendAutoDescription":
          "Использовать лучший доступный способ для устройства",
      "mirrorBackendWindowManager": "WindowManager",
      "mirrorBackendSurfaceControl": "SurfaceControl",
      "mirrorBackendVirtualDisplay": "VirtualDisplay",
      "updateAvailable": "Доступно обновление",
      "updateAvailableTitle": "На GitHub опубликована новая версия!",
      "playUpdateAvailableTitle": "В Google Play доступно обновление",
      "playUpdateAvailableDescription":
          "Вы можете обновить приложение до последней версии через Google Play.",
      "updateNow": "Обновить сейчас",
      "checkForUpdates": "Проверить обновления",
      "checkingForUpdates": "Получение сведений об обновлении",
      "updateNotChecked": "Сведения об обновлении ещё не получены",
      "upToDate": "Установлена последняя версия",
      "updateCheckFailed": "Не удалось получить сведения об обновлении",
      "currentVersion": "Текущая версия",
      "latestVersion": "Последняя версия",
      "openOnGitHub": "Открыть на GitHub",
      "close": "Закрыть",
      "deviceInfo": "Информация об устройстве",
      "desktopMode": "Режим рабочего стола",
      "accessibilitySettings": "Специальные возможности",
      "accessibilityDescription": "Открыть настройки службы Dextop",
      "appInfo": "О приложении",
      "licenses": "Лицензии открытого ПО",
      "licensesDescription": "Лицензии Flutter и используемых библиотек",
      "landscape": "Альбомная",
      "portrait": "Портретная",
      "stopped": "Остановлено",
      "running": "Работает",
      "start": "Запустить",
      "stop": "Остановить",
      "customAdd": "Добавить разрешение",
      "editResolution": "Изменить разрешение",
      "add": "Добавить",
      "save": "Сохранить",
      "deleteResolution": "Удалить разрешение",
      "width": "Ширина",
      "height": "Высота",
      "protectedContent": "Разрешить показ защищённого содержимого",
      "version": "Версия 1.0.0",
      "setupWelcome": "Добро пожаловать в Dextop.",
      "setupTagline": "Идеальная среда рабочего стола на вашем смартфоне.",
      "setupBegin": "Начать",
      "setupPhaseTerms": "Перед началом работы",
      "setupPhaseShizuku": "Shizuku",
      "setupPhaseDevice": "Проверка устройства",
      "setupPhaseDemo": "Знакомство с управлением",
      "back": "Назад",
      "continueLabel": "Продолжить",
      "done": "Готово",
      "incomplete": "Не завершено",
      "setupSystemTitle": "Использование системных функций",
      "setupSystemDescription":
          "Dextop использует Shizuku и ADB для управления таким поведением, как виртуальные дисплеи, ориентация экрана, ввод и системный пользовательский интерфейс.",
      "setupDisclaimer":
          "Разработчик не несет ответственности за любые дефекты, потерю данных или влияние на функциональность устройства, вызванное различиями в реализации устройства или ОС, обновлениями системы, конфликтами с другими приложениями и т. д. Перед использованием ознакомьтесь с содержанием.",
      "setupShizukuTitle": "Подготовка Shizuku",
      "setupShizukuDescription":
          "Dextop использует Shizuku для безопасного доступа к функциям системы.",
      "setupInstallShizuku": "Установить Shizuku",
      "setupConfigureShizuku": "Настроить Shizuku",
      "setupShizukuHint":
          "Откройте Shizuku, установите его в порядке, указанном в разделе «Сопряжение», и запустите Shizuku.",
      "setupOpenShizuku": "Открыть Shizuku",
      "setupValidate": "Настройка завершена? Проверить",
      "setupDextopPermission": "Разрешения для Dextop",
      "setupInstallPlay": "Установить из Google Play",
      "setupAllowPermission": "Предоставить разрешение",
      "setupProviderChoiceTitle": "Выберите привилегированную службу",
      "setupProviderChoiceDescription":
          "Установлены Stellar и Shizuku. Выберите службу, которую будет использовать Dextop.",
      "setupUseStellar": "Stellar (рекомендуется)",
      "setupUseShizuku": "Shizuku",
      "setupRunningAsRoot": "Служба запущена с правами root",
      "setupRootVerified":
          "Подтверждено, что Shizuku работает с правами root. Теперь предоставьте разрешение Dextop.",
      "setupRootNotRunning":
          "Не удалось подтвердить, что Shizuku работает с правами root. Запустите его с правами root и повторите попытку.",
      "setupQuestionOpen": "Вы открыли Shizuku?",
      "setupQuestionPair":
          "Вы выполнили все шаги, перечисленные в разделе «Сопряжение»?",
      "setupQuestionStart":
          "Вы нажали «Запустить» в Shizuku и убедились, что отображается сообщение «Shizuku работает»?",
      "yes": "Да",
      "no": "Нет",
      "setupVerified": "Настройка Shizuku проверена",
      "setupVerificationFailed":
          "Невозможно подтвердить конфигурацию или запуск Shizuku. Пожалуйста, выполните действия в Shizuku, а затем проверьте еще раз.",
      "setupPermissionCheckFailed":
          "Не удалось проверить разрешения для Shizuku.",
      "setupDeviceTitle": "Конфигурация на этом устройстве",
      "model": "Модель",
      "vendor": "Производитель",
      "desktopUi": "Интерфейс рабочего стола",
      "detectedResolution": "Автоматически определённое разрешение",
      "loadingLabel": "Загрузка…",
      "setupDeviceDescription":
          "Эта информация используется для установки исходного разрешения и элементов управления рабочим столом для конкретного устройства.",
      "setupGestureTitle": "Вызов панели управления жестами",
      "setupGestureDescription":
          "Поместите три пальца одновременно на три круга внизу.",
      "uiTwoFingerTap": "Касание двумя пальцами",
      "ui3FingerTap": "Касание тремя пальцами",
      "ui4Divisions": "Разделение на четыре области",
      "uiDextopIsReady": "Dextop готов.",
      "uiStopDextop": "Остановить Dextop",
      "uiDextopCanBeRestarted": "Сеанс Dextop можно возобновить",
      "uiOpenDextop": "Открыть Dextop",
      "uiCreateADextopSession": "Создать сеанс Dextop",
      "uiDextopWorkspaceJson": "Рабочая область Dextop в формате JSON",
      "uiPerformanceDisplayOnDextop":
          "Показывать панель производительности в Dextop",
      "uiDoNotSleepWhileRunningDextop":
          "Не выключать экран во время работы Dextop",
      "uiRealTimeDisplayOfFpsMemoryPower":
          "Отображение в реальном времени FPS, памяти, энергопотребления и заряда батареи.",
      "uiCouldNotLoadJson": "Не удалось загрузить JSON",
      "uiSecureSettingsPermission": "Разрешение на настройки безопасности",
      "uiAllowShizukuPermissions": "Предоставить разрешение Shizuku",
      "uiInstallShizuku": "Установить Shizuku",
      "uiCheckingShizukuConnection": "Проверка подключения к Shizuku",
      "uiShizukuConnection": "Подключение к Shizuku",
      "uiCopy": " — копия",
      "uiOthers": "Другое",
      "uiAccessibilityOverlay": "Оверлей специальных возможностей",
      "uiAccessibilityServices": "Служба специальных возможностей",
      "uiAppNotFound": "Приложение не найдено",
      "uiAppsAndWorkspace": "Приложения и рабочее пространство",
      "uiLaunchTheAppAndConfigureYourWorkspace":
          "Запуск приложений и настройка рабочих областей",
      "uiRestartTheApp": "Перезапустить приложение",
      "uiSearchApp": "Поиск приложений",
      "uiAppMemory": "Память приложения",
      "uiAppLauncher": "Панель приложений",
      "uiAppLauncherSettings": "Настройки запуска приложений",
      "uiAppLaunchFunction": "Функция запуска приложения",
      "uiImport": "Импортировать",
      "uiExport": "Экспортировать",
      "uiCursor": "Курсор",
      "uiCancel": "Отмена",
      "uiQuickSettingsTile": "Плитка быстрых настроек",
      "uiGesture": "Жест",
      "uiSecondaryIme": "Вторичный IME",
      "uiSecureDisplayFoldable":
          "Защищённый экран, способ зеркалирования, складные устройства",
      "uiSecurity": "Безопасность",
      "uiTap": "Касание",
      "uiTapPressAndHoldMultiFingerOperation":
          "Касание, долгое нажатие и управление несколькими пальцами",
      "uiOpenAppOnDesktop": "Открыть приложение на рабочем столе",
      "uiDesktopMode": "Режим рабочего стола",
      "uiDesktopFeatures": "Функции рабочего стола",
      "uiTrackpad": "Трекпад",
      "uiDrag": "Перетаскивание",
      "uiBattery": "Батарея",
      "uiPerformance": "Производительность",
      "uiPerformanceCompatibility": "Производительность и совместимость",
      "uiItSupportsMultiTouchAndTheThree":
          "Включает мультитач и заменяет жест тремя пальцами на свайп от левого края экрана.",
      "uiMainLarge2Sub": "Большое основное окно + два дополнительных",
      "uiMainLeft": "Главный (слева)",
      "uiLayout": "Расположение",
      "uiWorkSpace": "Рабочая область",
      "uiCopiedWorkspaceJsonToClipboard":
          "JSON рабочей области скопирован в буфер обмена.",
      "uiImportWorkspace": "Импорт рабочей области",
      "uiSaveWorkspace": "Сохранить рабочее пространство",
      "uiDeleteWorkspace": "Удалить рабочую область",
      "uiEditWorkspace": "Изменить рабочую область",
      "uiUp": "Переместить вверх",
      "uiDividedIntoUpperAndLowerParts": "Разделение сверху и снизу",
      "uiUpperHalf": "Верхняя половина",
      "uiMoveDown": "Переместить вниз",
      "uiLowerHalf": "Нижняя половина",
      "uiCenter": "По центру",
      "uiCompatibilityDiagnosis": "Диагностика совместимости",
      "uiVirtualDisplayCreation": "Создание виртуального дисплея",
      "uiOpenASavedAppConfiguration":
          "Откройте сохраненную конфигурацию приложения",
      "uiNoSavedWorkspaces": "Нет сохраненных рабочих пространств",
      "uiInputAndGestures": "Ввод и жесты",
      "uiInputMode": "Режим ввода",
      "uiCancelFullScreen": "Выйти из полноэкранного режима",
      "uiReDiagnosis": "Повторить диагностику",
      "uiRestart": "Возобновить",
      "uiAvailableMemory": "Доступная память",
      "uiDelete": "Удалить",
      "uiYouCanRestoreYourPreviousSession":
          "Вы можете восстановить предыдущий сеанс",
      "uiRight": "Справа",
      "uiRight13": "Правая 1/3",
      "uiRight23": "Справа 2/3",
      "uiRightClick": "Щелчок правой кнопкой",
      "uiUpperRight": "Справа сверху",
      "uiLowerRight": "Справа снизу",
      "uiRightHalf": "Правая половина",
      "uiName": "Название",
      "uiLargeScreenFoldable": "Большой экран/складной",
      "uiActualFps": "Фактический FPS",
      "uiExperimentalMultiTouch": "Экспериментальный мультитач",
      "uiExperimentalFeatures": "Экспериментальные функции",
      "uiLeft": "Слева",
      "uiLeft13": "Слева 1/3",
      "uiLeft13Right23": "Слева 1/3 + справа 2/3",
      "uiLeft23": "Слева 2/3",
      "uiLeft23Right13": "Слева 2/3 + справа 1/3",
      "uiLeftCenterRight": "Слева / по центру / справа",
      "uiUpperLeft": "Слева сверху",
      "uiUpperLeftUpperRightLowerHalf":
          "Верхний левый, верхний правый, нижняя половина",
      "uiLowerLeft": "Слева снизу",
      "uiLeftHalf": "Левая половина",
      "uiDividedIntoLeftAndRight": "Разделение слева и справа",
      "uiSwipeRightWithThreeFingersFromThe":
          "Проведите тремя пальцами вправо от левого края",
      "uiRecoverySession": "Восстановление сеанса",
      "uiEstimatedPowerConsumption": "Расчетное энергопотребление",
      "uiOperationOverlay": "Панель управления",
      "uiShowActionOverlay": "Показать панель управления",
      "uiOperationMenu": "Меню управления",
      "uiThereIsAnExistingSession": "Обнаружен существующий сеанс",
      "uiSaveConfiguration": "Сохранить конфигурацию",
      "uiRestorePrivileges": "Восстановить разрешения",
      "uiChangeToHorizontalHold": "Переключить в альбомную ориентацию",
      "uiPreparationIsRequired": "Требуется настройка",
      "uiPhysicalKeyboard": "Физическая клавиатура",
      "uiPhysicalMouse": "Физическая мышь",
      "uiConditionAndDiagnosis": "Состояние и диагностика",
      "uiPreventsTheScreenFromTurningOffAutomatically":
          "Предотвращает автоматическое выключение экрана",
      "uiDestruction": "Удалить",
      "uiTerminalAndPermissions": "Устройство и разрешения",
      "uiDeviceInformationDesktopModeAccessibility":
          "Информация об устройстве, режим рабочего стола, специальные возможности",
      "uiTerminalResolution": "Разрешение устройства",
      "uiEnd": "Завершить",
      "uiTerminationProcessingCompletedSuccessfully": "Сеанс успешно завершён.",
      "uiEdit": "Изменить",
      "uiChangeToPortraitOrientation": "Переключиться на портретную ориентацию",
      "uiVerticalHorizontalSwitching": "Портретная / альбомная ориентация",
      "uiDisplayOptimization": "Оптимизация дисплея",
      "uiDisplayRefreshRate": "Частота обновления дисплея",
      "uiReproduction": "Создать копию",
      "uiManageLaunchedAppsAndConfigurations":
          "Управление запускаемыми приложениями и их расположением",
      "uiCouldNotStart": "Не удалось запустить",
      "uiLongPress": "Долгое нажатие",
      "uiAutomaticallyUsesMeasuredResolutionForOpenAnd":
          "Автоматически использует измеренное разрешение для открытых и закрытых состояний.",
      "uiStart": "Начать",
      "uiAutomaticSwitchingAccordingToOpenClosedState":
          "Автоматическое переключение в зависимости от открытого/закрытого состояния.",
      "uiOpeningQuote": "«",
      "uiDeleteWorkspaceQuestionSuffix":
          "» — удалить это рабочее пространство?",
      "uiAbnormalSessionWarning":
          "Сеанс завершился в некорректном состоянии.\nНекоторые системные функции Android могут оставаться отключёнными.",
      "uiChecking": "Проверка",
      "uiIdle": "Ожидание",
      "uiAvailable": "Available",
      "uiUnavailable": "Unavailable",
      "appName": "Dextop",
      "uiAndroid": "Android",
      "uiGitHub": "GitHub",
      "uiGitHubRepository": "NarYuki/Dextop",
      "diagnosticLog": "Журнал работы и диагностика устройства",
      "diagnosticLogDescription":
          "Журналы приложения, проверка возможностей и характеристики устройства",
      "loadDiagnosticLog": "Загрузить отчёт диагностики",
      "copyDiagnosticLog": "Копировать",
      "shareDiagnosticLog": "Поделиться",
      "clearDiagnosticLog": "Очистить журнал",
      "deviceReport": "Отчёт о работе устройства",
      "uiCpuTemperature": "Температура ЦП",
      "deviceReportDescription":
          "Отправить совместимость устройства и функций по электронной почте",
      "deviceReportIntro":
          "Данные устройства собираются автоматически. Выберите результат для каждой функции.",
      "reportWorking": "Работает",
      "reportNotWorking": "Не работает",
      "reportUntested": "Не проверено",
      "reportOverall": "Общий статус",
      "reportNotes": "Другие примечания",
      "sendDeviceReport": "Отправить отчёт по почте",
      "reportEmailUnavailable": "Не удалось открыть почтовое приложение",
      "reportTemplateTitle": "Отчёт о работе Dextop",
      "reportNoNotes": "Нет",
      "reportNoSessionLog":
          "Журнал завершённого сеанса Dextop пока отсутствует.",
      "reportFeatureStartup": "Запуск приложения и обнаружение устройства",
      "reportFeatureSession": "Запуск сеанса Dextop",
      "reportFeatureVirtualDisplay": "Зеркалирование VirtualDisplay",
      "reportFeatureWindowManager": "Зеркалирование WindowManager",
      "reportFeatureSurfaceControl": "Зеркалирование SurfaceControl",
      "reportFeatureLandscape": "Альбомный режим",
      "reportFeaturePortrait": "Портретный режим",
      "reportFeatureSecureDisplay": "Защищённый дисплей",
      "reportFeatureLauncher": "Панель приложений и свободные окна",
      "reportFeatureWorkspace": "Сохранение и восстановление рабочих областей",
      "reportFeatureCursor": "Ввод курсором и сенсорной панелью",
      "reportFeatureDirectTouch": "Прямой сенсорный ввод",
      "reportFeatureMultiTouch": "Мультитач-прокрутка и масштабирование",
      "reportFeatureGesture": "Жест оверлея тремя пальцами",
      "reportFeatureMouse": "Физическая мышь",
      "reportFeatureKeyboard": "Физическая клавиатура",
      "reportFeatureRouting": "Маршрутизация мыши и клавиатуры между дисплеями",
      "reportFeatureFoldable": "Авторазрешение для складных устройств",
      "reportFeaturePerformance": "Оверлей производительности",
      "reportFeatureCleanup": "Завершение сеанса и восстановление Android",
      "samsungExperimentalTitle":
          "Экспериментальные настройки рабочего стола Samsung",
      "samsungUnavailable": "Доступно только на устройствах Samsung",
      "samsungExperimentalDescription":
          "Изменение скрытых параметров DeX из Dextop",
      "samsungSettingsTitle": "Настройки рабочего стола Samsung",
      "samsungSettingsSummary": "Экран, ввод и панель задач",
      "samsungRestoreSuccess": "Настройки Samsung восстановлены",
      "samsungConfirmTitle": "Подтверждение изменения настроек",
      "samsungPermanentWarning":
          "Эти параметры могут постоянно влиять на Dextop и обычную среду рабочего стола до их сброса.",
      "samsungAcceptEnable": "Принять и включить",
      "samsungAboutSetting": "Об этом параметре",
      "samsungRestoreEnvironment": "Восстановить среду",
      "samsungSettingsIntro":
          "Напрямую изменяет значения DeX, скрытые настройками Samsung при отсутствии внешнего дисплея. Изменения влияют на Samsung DeX и соответствующие функции Dextop.",
      "samsungResolution": "Разрешение внешнего экрана",
      "samsungScreenZoom": "Масштаб экрана (DPI)",
      "samsungFontScale": "Размер шрифта",
      "samsungScreenTimeout": "Тайм-аут экрана",
      "samsungAudioOutput": "Вывод звука на внешний экран",
      "samsungDisplayOrientation": "Поворот внешнего экрана",
      "samsungDisplayArrangement": "Расположение экранов",
      "samsungSectionInput": "Ввод",
      "samsungSectionDesktop": "Рабочий стол",
      "samsungInputLockedWhileRunning":
          "Конфликтующие параметры ввода Samsung нельзя менять во время работы Dextop.",
      "samsungAutorunTouchpad": "Автоматически запускать сенсорную панель",
      "samsungTouchpadScrollDirection": "Обратное направление прокрутки",
      "samsungTouchKeyboard": "Показывать экранную клавиатуру при подключении",
      "samsungKeyboardDex": "Показывать клавиатуру при физической клавиатуре",
      "samsungSpenInputMode": "Использовать S Pen как мышь",
      "samsungThreeFingerGesture": "Жест тремя пальцами",
      "samsungFourFingerGesture": "Жест четырьмя пальцами",
      "samsungAutoHideTaskbar": "Автоматически скрывать панель задач",
      "samsungDexCommandArrow": "Показывать стрелку команд",
      "samsungIncludePhoneDisplay": "Включить экран телефона в топологию",
      "samsungMirrorPhoneDisplay": "Дублировать встроенный экран",
      "samsungReviewEnable": "Прочитать предупреждение и разрешить изменения",
      "samsungSeconds15": "15 секунд",
      "samsungSeconds30": "30 секунд",
      "samsungMinute1": "1 минута",
      "samsungMinutes2": "2 минуты",
      "samsungMinutes5": "5 минут",
      "samsungMinutes10": "10 минут",
      "samsungMinutes20": "20 минут",
      "samsungMinutes30": "30 минут",
      "samsungHour1": "1 час",
      "samsungLeft": "Слева",
      "samsungRight": "Справа",
      "samsungAutomatic": "Автоматически",
      "samsungGestureNone": "Нет",
      "samsungGestureApps": "Приложения",
      "samsungGestureRecents": "Недавние",
      "samsungGestureNotifications": "Уведомления",
      "samsungGestureQuickSettings": "Быстрые настройки",
      "samsungHelp_resolution":
          "Разрешение внешнего экрана Samsung Desktop, хранящееся отдельно от разрешения Dextop.",
      "samsungHelp_screenZoom":
          "Изменяет плотность отображения (DPI) рабочего стола Samsung.",
      "samsungHelp_fontScale":
          "Изменяет масштаб текста рабочего стола Samsung.",
      "samsungHelp_screenTimeout": "Время до отключения внешнего экрана.",
      "samsungHelp_audioOutput": "Переключает вывод звука на внешний экран.",
      "samsungHelp_displayOrientation": "Фиксирует ориентацию внешнего экрана.",
      "samsungHelp_displayArrangement":
          "Задаёт взаимное расположение телефона и внешнего экрана.",
      "samsungHelp_autorunTouchpad":
          "Автоматически запускает панель Samsung и конфликтует с вводом Dextop.",
      "samsungHelp_touchpadScrollDirection":
          "Меняет направление прокрутки панели Samsung.",
      "samsungHelp_touchKeyboard":
          "Показывает экранную клавиатуру и конфликтует с IME Dextop.",
      "samsungHelp_keyboardDex":
          "Оставляет экранную клавиатуру при физической и конфликтует с IME Dextop.",
      "samsungHelp_spenInputMode":
          "Использует S Pen как указывающее устройство.",
      "samsungHelp_threeFingerGesture":
          "Жест Samsung тремя пальцами конфликтует с жестами Dextop.",
      "samsungHelp_fourFingerGesture":
          "Жест Samsung четырьмя пальцами конфликтует с мультитачем Dextop.",
      "samsungHelp_autoHideTaskbar":
          "Автоматически скрывает панель задач Samsung Desktop.",
      "samsungHelp_dexCommandArrow":
          "Показывает стрелку команд Samsung Desktop.",
      "samsungHelp_includePhoneDisplay":
          "Включает экран телефона в топологию рабочего стола.",
      "samsungHelp_mirrorPhoneDisplay":
          "Дублирует встроенный экран в среду рабочего стола.",
    },
  };
}
